package main

import (
	"fmt"
	"strings"
)

const runtimeABIVersion = 2

const runtimeMailboxVersion = 1

const runtimeMailboxMagic = "0x4d585347"

const runtimeMailboxHeaderBytes = 24

type runtimeABIMethod struct {
	name   string
	params string
	result string
}

var runtimeABIMethods = []runtimeABIMethod{
	{name: "abiVersion", result: "number"},
	{name: "featureMask", result: "number"},
	{name: "alloc", params: "size: number", result: "number"},
	{name: "hydrate", params: "ptr: number, size: number", result: "number"},
	{name: "dispatch", params: "handle: number, eventID: number, ptr: number, size: number", result: "number"},
	{name: "responsePtr", result: "number"},
	{name: "responseSize", result: "number"},
	{name: "dispose", params: "handle: number", result: "void"},
}

// runtimeContractTypeScript renders the versioned browser/WASM contract. The
// Go runtime owns the executable codec; this generated file keeps the browser
// compiler and route tooling on the same constants and direct-export shape.
func runtimeContractTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/buildbootstrap runtimeContractTypeScript. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "export const GOSX_RUNTIME_ABI_VERSION = %d as const;\n\n", runtimeABIVersion)
	fmt.Fprintf(&b, "export const GOSX_RUNTIME_MAILBOX_VERSION = %d as const;\n", runtimeMailboxVersion)
	fmt.Fprintf(&b, "export const GOSX_RUNTIME_MAILBOX_MAGIC = %s as const;\n", runtimeMailboxMagic)
	fmt.Fprintf(&b, "export const GOSX_RUNTIME_MAILBOX_HEADER_BYTES = %d as const;\n\n", runtimeMailboxHeaderBytes)
	b.WriteString("export const GOSX_RUNTIME_FEATURE_CORE = 1 << 0;\n")
	b.WriteString("export const GOSX_RUNTIME_FEATURE_ENGINE = 1 << 1;\n")
	b.WriteString("export const GOSX_RUNTIME_FEATURE_COLLAB = 1 << 2;\n")
	b.WriteString("export const GOSX_RUNTIME_FEATURE_SCENE3D = 1 << 3;\n")
	b.WriteString("export const GOSX_RUNTIME_FEATURE_ISLANDS = 1 << 4;\n\n")
	b.WriteString("export type GoSXFeatureMask = number;\n\n")
	b.WriteString("export type GoSXRuntimeVariant = \"core\" | \"engine\" | \"collab\" | \"full\" | \"islands\";\n\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_FLAG_RESPONSE = 1 << 0;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_STATUS_OK = 0;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_HANDSHAKE = 1;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_PING = 2;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_PATCHES = 3;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_ACTION = 4;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_INPUT_BATCH = 5;\n")
	b.WriteString("export const GOSX_RUNTIME_MAILBOX_OPCODE_ENGINE_FRAME = 6;\n\n")
	b.WriteString("export interface GoSXRuntimeHandshake {\n")
	b.WriteString("  readonly abiVersion: typeof GOSX_RUNTIME_ABI_VERSION;\n")
	b.WriteString("  readonly featureMask: GoSXFeatureMask;\n")
	b.WriteString("  readonly variant: GoSXRuntimeVariant;\n")
	b.WriteString("  readonly mailboxVersion: typeof GOSX_RUNTIME_MAILBOX_VERSION;\n")
	b.WriteString("  readonly manifestHash: string;\n")
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXRuntimeMailboxHeader {\n")
	b.WriteString("  readonly magic: typeof GOSX_RUNTIME_MAILBOX_MAGIC;\n")
	b.WriteString("  readonly version: typeof GOSX_RUNTIME_MAILBOX_VERSION;\n")
	b.WriteString("  readonly opcode: number;\n")
	b.WriteString("  readonly requestID: number;\n")
	b.WriteString("  readonly payloadSize: number;\n")
	b.WriteString("  readonly status: number;\n")
	b.WriteString("  readonly flags: number;\n")
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXCoreExports {\n")
	b.WriteString("  readonly memory?: WebAssembly.Memory;\n")
	for _, method := range runtimeABIMethods {
		fmt.Fprintf(&b, "  %s(%s): %s;\n", method.name, method.params, method.result)
	}
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXRuntimeDirectExports {\n")
	b.WriteString("  readonly abiVersion: number;\n")
	b.WriteString("  readonly featureMask: GoSXFeatureMask;\n")
	b.WriteString("  readonly variant: GoSXRuntimeVariant;\n")
	b.WriteString("  readonly mailboxVersion: typeof GOSX_RUNTIME_MAILBOX_VERSION;\n")
	b.WriteString("  handshake(): GoSXRuntimeHandshake;\n")
	b.WriteString("  mailbox(request: Uint8Array | ArrayBuffer): Uint8Array;\n")
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXRuntimeVariantAsset {\n")
	b.WriteString("  readonly file: string;\n")
	b.WriteString("  readonly hash: string;\n")
	b.WriteString("  readonly size: number;\n")
	b.WriteString("  readonly variant: GoSXRuntimeVariant;\n")
	b.WriteString("  readonly featureMask: GoSXFeatureMask;\n")
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXRuntimeManifestV2 {\n")
	b.WriteString("  readonly abiVersion: typeof GOSX_RUNTIME_ABI_VERSION;\n")
	b.WriteString("  readonly featureMask: GoSXFeatureMask;\n")
	b.WriteString("  readonly variant: GoSXRuntimeVariant;\n")
	b.WriteString("  readonly mailboxVersion: typeof GOSX_RUNTIME_MAILBOX_VERSION;\n")
	b.WriteString("  readonly manifestHash: string;\n")
	b.WriteString("  readonly wasmURL: string;\n")
	b.WriteString("  readonly wasmVariants?: Readonly<Record<GoSXRuntimeVariant, GoSXRuntimeVariantAsset>>;\n")
	b.WriteString("}\n")
	return b.String()
}
