package main

import (
	"fmt"
	"strings"

	runtimewasm "m31labs.dev/gosx/client/runtime/wasm"
)

// runtimeContractTypeScript renders the executable browser/WASM contract.
// Every value comes from the Go codec package. The generated file is included
// before abi.ts, mailbox.ts, and loader.ts in each runtime-capable bundle, so
// those consumers cannot silently drift onto hand-authored constants.
func runtimeContractTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/buildbootstrap runtimeContractTypeScript. DO NOT EDIT.\n")
	b.WriteString("// This is executable bundle input, not a declaration-only artifact.\n\n")
	b.WriteString("(function() {\n")
	b.WriteString("  \"use strict\";\n")
	b.WriteString("  if (typeof window === \"undefined\" || window.__gosx_runtime_contract) return;\n")
	b.WriteString("  window.__gosx_runtime_contract = Object.freeze({\n")
	fmt.Fprintf(&b, "    abiVersion: %d,\n", runtimewasm.ABIVersion)
	fmt.Fprintf(&b, "    mailboxVersion: %d,\n", runtimewasm.MailboxVersion)
	fmt.Fprintf(&b, "    manifestHash: %q,\n", runtimewasm.ManifestIdentity())
	fmt.Fprintf(&b, "    mailboxMagic: %d,\n", runtimewasm.MailboxMagic)
	fmt.Fprintf(&b, "    mailboxHeaderBytes: %d,\n", runtimewasm.MailboxHeaderSize)
	fmt.Fprintf(&b, "    mailboxMaxPayload: %d,\n", runtimewasm.MaxMailboxPayload)
	fmt.Fprintf(&b, "    mailboxFlagResponse: %d,\n", runtimewasm.MailboxFlagResponse)
	fmt.Fprintf(&b, "    mailboxStatusOK: %d,\n", runtimewasm.MailboxStatusOK)
	b.WriteString("    features: Object.freeze({\n")
	fmt.Fprintf(&b, "      core: %d, engine: %d, collab: %d, scene3d: %d, islands: %d,\n",
		runtimewasm.FeatureCore, runtimewasm.FeatureEngine, runtimewasm.FeatureCollab,
		runtimewasm.FeatureScene3D, runtimewasm.FeatureIslands)
	b.WriteString("    }),\n")
	b.WriteString("    variants: Object.freeze({\n")
	for _, variant := range []runtimewasm.Variant{
		runtimewasm.VariantCore,
		runtimewasm.VariantIslands,
		runtimewasm.VariantEngine,
		runtimewasm.VariantCollab,
		runtimewasm.VariantFull,
	} {
		fmt.Fprintf(&b, "      %s: %d,\n", variant, runtimewasm.FeatureMaskForVariant(variant))
	}
	b.WriteString("    }),\n")
	b.WriteString("    opcodes: Object.freeze({\n")
	fmt.Fprintf(&b, "      handshake: %d, ping: %d, patches: %d,\n",
		runtimewasm.MailboxOpcodeHandshake, runtimewasm.MailboxOpcodePing,
		runtimewasm.MailboxOpcodePatches)
	b.WriteString("    }),\n")
	fmt.Fprintf(&b, "    directMailboxOpcodes: Object.freeze([%d, %d]),\n",
		runtimewasm.MailboxOpcodeHandshake, runtimewasm.MailboxOpcodePing)
	b.WriteString("  });\n")
	b.WriteString("})();\n")
	return b.String()
}
