package main

import (
	"fmt"
	"strings"
)

const runtimeABIVersion = 1

type runtimeABIMethod struct {
	name   string
	params string
	result string
}

var runtimeABIMethods = []runtimeABIMethod{
	{name: "abiVersion", result: "number"},
	{name: "featureMask", result: "number"},
	{name: "alloc", params: "size: number", result: "number"},
	{name: "hydrate", params: "ptr: number, size: number", result: "number"},
	{name: "dispatch", params: "handle: number, eventID: number, ptr: number, size: number", result: "number"},
	{name: "responsePtr", result: "number"},
	{name: "responseSize", result: "number"},
	{name: "dispose", params: "handle: number", result: "void"},
}

// runtimeContractTypeScript renders the first versioned browser/WASM contract.
// O0.1 keeps the schema local to the build tool. A shared Go package can own
// the schema when O4 adds TinyGo export generation and binary codecs.
func runtimeContractTypeScript() string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/buildbootstrap runtimeContractTypeScript. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "export const GOSX_RUNTIME_ABI_VERSION = %d as const;\n\n", runtimeABIVersion)
	b.WriteString("export type GoSXFeatureMask = number;\n\n")
	b.WriteString("export interface GoSXCoreExports {\n")
	b.WriteString("  readonly memory: WebAssembly.Memory;\n")
	for _, method := range runtimeABIMethods {
		fmt.Fprintf(&b, "  %s(%s): %s;\n", method.name, method.params, method.result)
	}
	b.WriteString("}\n\n")
	b.WriteString("export interface GoSXRuntimeManifestV1 {\n")
	b.WriteString("  readonly abiVersion: typeof GOSX_RUNTIME_ABI_VERSION;\n")
	b.WriteString("  readonly featureMask: GoSXFeatureMask;\n")
	b.WriteString("  readonly manifestHash: string;\n")
	b.WriteString("  readonly wasmURL: string;\n")
	b.WriteString("}\n")
	return b.String()
}
