//go:build !tinygo

package gosx

import (
	"strings"
	"testing"
)

// gosx#139: an app staged a dist/gosx-grammar.blob generated by a different
// gosx checkout. SetGrammarBlob accepted it, and the stale parse tables
// failed context-dependently on real markup with no error node to report.
// The override gate is a byte fingerprint against the embedded blob: a
// mismatch is refused so Language() falls back to the embedded grammar.

func TestSetGrammarBlobRejectsMismatchedOverride(t *testing.T) {
	if len(embeddedGrammarBlob) == 0 {
		t.Skip("no embedded grammar blob in this build")
	}

	stale := append([]byte(nil), embeddedGrammarBlob...)
	stale[len(stale)/2] ^= 0xFF

	err := SetGrammarBlob(stale)
	if err == nil {
		t.Fatal("SetGrammarBlob accepted a mismatched override")
	}
	if !strings.Contains(err.Error(), "does not match the blob embedded") {
		t.Fatalf("mismatch error should name the cause, got %q", err)
	}

	// The refused override must not poison the language cache: parsing
	// still works through the embedded blob.
	if _, err := Compile([]byte("package app\nfunc Page() Node {\n\treturn <div>ok</div>\n}\n")); err != nil {
		t.Fatalf("Compile after refused override: %v", err)
	}
}

func TestSetGrammarBlobAcceptsMatchingOverride(t *testing.T) {
	if len(embeddedGrammarBlob) == 0 {
		t.Skip("no embedded grammar blob in this build")
	}
	if err := SetGrammarBlob(append([]byte(nil), embeddedGrammarBlob...)); err != nil {
		t.Fatalf("SetGrammarBlob rejected a byte-identical override: %v", err)
	}
}
