"use strict";

// Unit tests for the pure skinned-shadow GLB fixture helper. The browser-probe
// registration path requires this helper directly, so these tests pin the
// fixture contract (baked geometry, identity model root, single-joint skin,
// constant pose clip) against the ACTUAL generated bytes. A second group
// below executes the ACTUAL probe skinned helpers via a vm source slice.

const { test } = require("node:test");
const assert = require("node:assert/strict");
const path = require("node:path");
const fs = require("node:fs");
const vm = require("node:vm");

const FIXTURE = require(path.join(__dirname, "testdata", "skinned-shadow-fixture.cjs"));

function parseGlbJson(buffer) {
  const jsonLen = buffer.readUInt32LE(12);
  const json = JSON.parse(buffer.subarray(20, 20 + jsonLen).toString("utf8"));
  const binHeader = 20 + jsonLen;
  const binLen = buffer.readUInt32LE(binHeader);
  return { json, bin: buffer.subarray(binHeader + 8, binHeader + 8 + binLen) };
}

// Test-owned GLB re-serializer: rebuilds a real GLB from mutated metadata so
// validation of bad declared byteLengths / targets runs on actual chunk bytes.
function rebuildGlb(json, bin) {
  let jsonBuf = Buffer.from(JSON.stringify(json), "utf8");
  const jp = (4 - (jsonBuf.length % 4)) % 4;
  if (jp) jsonBuf = Buffer.concat([jsonBuf, Buffer.alloc(jp, 0x20)]);
  const bp = (4 - (bin.length % 4)) % 4;
  const binP = bp ? Buffer.concat([bin, Buffer.alloc(bp)]) : bin;
  const header = Buffer.alloc(12);
  header.writeUInt32LE(0x46546C67, 0);
  header.writeUInt32LE(2, 4);
  header.writeUInt32LE(12 + 8 + jsonBuf.length + 8 + binP.length, 8);
  const jh = Buffer.alloc(8);
  jh.writeUInt32LE(jsonBuf.length, 0);
  jh.writeUInt32LE(0x4E4F534A, 4);
  const bh = Buffer.alloc(8);
  bh.writeUInt32LE(binP.length, 0);
  bh.writeUInt32LE(0x004E4942, 4);
  return Buffer.concat([header, jh, jsonBuf, bh, binP]);
}

test("skinned-shadow fixture builds and validates rest + pose GLBs", () => {
  const fx = FIXTURE.buildSkinnedShadowFixture();
  const rest = Buffer.from(fx.rest, "base64");
  const pose = Buffer.from(fx.pose, "base64");
  FIXTURE.validateSkinnedShadowGLB(rest, false);
  FIXTURE.validateSkinnedShadowGLB(pose, true);
  assert.equal(fx.meta.vertexCount, 24);
  assert.equal(fx.meta.indexCount, 36);
  assert.equal(fx.meta.triangleCount, 12);
  assert.equal(fx.meta.poseX, 0.8);
  assert.deepEqual(fx.meta.sceneRoots, [0, 1]);
  assert.deepEqual(fx.meta.center, [-0.55, 0.35, 0.5]);
  assert.deepEqual(fx.meta.size, [0.55, 0.55, 0.15]);
  // Declared buffer byteLength is the ACTUAL final BIN length: geometry
  // views total 1480 bytes; the pose clip adds 8 (times) + 24 (vals) = 32.
  assert.equal(parseGlbJson(rest).json.buffers[0].byteLength, 1480);
  assert.equal(parseGlbJson(pose).json.buffers[0].byteLength, 1512);
  // Real GLB chunk headers, not just parseable JSON.
  assert.equal(rest.readUInt32LE(0), 0x46546C67);
  assert.equal(rest.readUInt32LE(8), rest.length);
  assert.equal(pose.readUInt32LE(0), 0x46546C67);
  assert.equal(pose.readUInt32LE(8), pose.length);
});

test("rest GLB has no clip; pose GLB clip translates joint node 1 by +0.8x", () => {
  const fx = FIXTURE.buildSkinnedShadowFixture();
  const rest = parseGlbJson(Buffer.from(fx.rest, "base64")).json;
  const pose = parseGlbJson(Buffer.from(fx.pose, "base64")).json;
  assert.ok(!rest.animations || rest.animations.length === 0, "rest has no animation");
  assert.equal(pose.animations.length, 1);
  assert.equal(pose.animations[0].name, "pose");
  assert.equal(pose.animations[0].channels[0].target.node, 1);
  assert.equal(pose.animations[0].channels[0].target.path, "translation");
  // Model root identity and skin wiring on the actual parsed nodes.
  assert.equal(pose.nodes[0].translation, undefined);
  assert.equal(pose.nodes[1].translation, undefined);
  assert.equal(pose.nodes[0].skin, 0);
  assert.deepEqual(pose.scenes[0].nodes, [0, 1]);
  assert.deepEqual(pose.skins[0].joints, [1]);
});

test("validation rejects truncated GLBs (missing evidence never passes)", () => {
  const fx = FIXTURE.buildSkinnedShadowFixture();
  const b = Buffer.from(fx.rest, "base64");
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(b.subarray(0, b.length - 4), false));
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(Buffer.alloc(8), false));
});

test("validation rejects mutated bad metadata on rebuilt GLB bytes", () => {
  const fx = FIXTURE.buildSkinnedShadowFixture();
  const { json, bin } = parseGlbJson(Buffer.from(fx.pose, "base64"));
  const m1 = JSON.parse(JSON.stringify(json));
  m1.buffers[0].byteLength = bin.length + 16;
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(rebuildGlb(m1, bin), true));
  const m2 = JSON.parse(JSON.stringify(json));
  m2.buffers[0].byteLength = bin.length - 16;
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(rebuildGlb(m2, bin), true));
  const m3 = JSON.parse(JSON.stringify(json));
  m3.bufferViews[0].target = 9999;
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(rebuildGlb(m3, bin), true));
  const m4 = JSON.parse(JSON.stringify(json));
  m4.bufferViews[6].target = 34963;
  assert.throws(() => FIXTURE.validateSkinnedShadowGLB(rebuildGlb(m4, bin), true),
    /inverseBind bufferView must omit target/);
});

// ---- ACTUAL probe skinned-helper regression (vm slice, not copies) ----
// These cases execute the REAL helper source from the probe file: the slice
// runs from `function skinMatrixMatches` through the overall watchdog, and
// the case-registration extraction runs the actual addSkinnedShadowCases
// body against a fresh CASES=[]. No full probe execution and no claimed
// native certification here.

const PROBE_CJS = path.join(__dirname, "testdata",
  "scene3d-material-ior-browser.cjs");

function loadProbeSkinHelpers() {
  const src = fs.readFileSync(PROBE_CJS, "utf8");
  const start = src.indexOf("function skinMatrixMatches");
  const end = src.indexOf("// ---- Overall watchdog");
  assert.ok(start >= 0, "probe source has skinMatrixMatches anchor");
  assert.ok(end > start, "probe source helper-slice end anchor");
  const ctx = {};
  vm.createContext(ctx);
  vm.runInContext(src.slice(start, end), ctx);
  assert.equal(typeof ctx.skinMatrixMatches, "function");
  assert.equal(typeof ctx.skinStateReady, "function");
  assert.equal(typeof ctx.skinDrawMatches, "function");
  assert.equal(typeof ctx.runSkinnedShadowLiveSteps, "function");
  assert.equal(typeof ctx.skinLiveHubDetail, "function");
  // Normalize through JSON: cross-VM object prototypes must not affect the
  // structural comparison of these plain payloads.
  assert.deepStrictEqual(JSON.parse(JSON.stringify(ctx.skinLiveHubDetail("pose"))), {
    event: "skin-pose",
    data: { "skin-caster": { animation: "pose", loop: true,
      animationFadeInMS: 0, animationFadeOutMS: 0 } },
  });
  assert.deepStrictEqual(JSON.parse(JSON.stringify(ctx.skinLiveHubDetail(""))), {
    event: "skin-pose",
    data: { "skin-caster": { animation: "", loop: false,
      animationFadeInMS: 0, animationFadeOutMS: 0 } },
  });
  return ctx;
}

function loadProbeSkinnedShadowCases() {
  const src = fs.readFileSync(PROBE_CJS, "utf8");
  const start = src.indexOf("function addSkinnedShadowCases");
  const call = src.indexOf("addSkinnedShadowCases();", start);
  assert.ok(start >= 0, "probe source has addSkinnedShadowCases anchor");
  assert.ok(call > start, "probe source registration call anchor");
  const ctx = {
    CASES: [],
    SK_LIGHTS: [],
    SK_RECEIVER: { id: "sk-receiver" },
    ROI: { x: 0, y: 0, width: 2, height: 2 },
  };
  vm.createContext(ctx);
  vm.runInContext(src.slice(start, call) + "\naddSkinnedShadowCases();", ctx);
  return ctx.CASES;
}

const SK_IDENTITY = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
function skTxMatrix(tx) {
  const m = SK_IDENTITY.slice();
  m[12] = tx;
  return m;
}
function skValidState(opts) {
  opts = opts || {};
  return { skinState: {
    records: 1, recordID: "skin-caster",
    hasMixer: opts.mixer === true, animation: opts.animation || "",
    rootTransform: SK_IDENTITY.slice(),
    palette: skTxMatrix(opts.paletteTx || 0), paletteLength: 16,
    animationApiCapabilities: opts.apiMissing ? false : true,
    animationApiMatchesRecord: opts.apiMismatch ? false : true,
    object: { id: "skin-caster", hasSkin: true, castShadow: true,
      jointsLength: 8, weightsLength: 8,
      joints: [0, 0, 0, 0, 1, 1, 1, 1],
      weights: [1, 0, 0, 0, 0.5, 0.5, 0, 0] } } };
}
function skValidDraw(opts) {
  opts = opts || {};
  return {
    draws: opts.draws === undefined ? 3 : opts.draws,
    lastHasSkin: opts.lastHasSkin === undefined ? true : opts.lastHasSkin,
    lastProgramId: (opts.lastProgramId === undefined) ? 42 : opts.lastProgramId,
    lastPalette0: (opts.lastPalette0 === undefined) ?
      skTxMatrix(opts.tx || 0) : opts.lastPalette0,
    lastModelMatrix: (opts.lastModelMatrix === undefined) ?
      SK_IDENTITY.slice() : opts.lastModelMatrix,
    lastOpacity: opts.lastOpacity === undefined ? 1 : opts.lastOpacity,
    lastAlphaCutoff: (opts.lastAlphaCutoff === undefined) ?
      -1 : opts.lastAlphaCutoff,
  };
}

test("actual probe helpers accept valid rest + pose state and native draws", () => {
  const H = loadProbeSkinHelpers();
  assert.equal(H.skinStateReady(skValidState(), {}, 0), true);
  assert.equal(H.skinStateReady(
    skValidState({ paletteTx: 0.8, animation: "pose", mixer: true }),
    { skinnedExpectPose: true, skinnedExpectMixer: true }, 0.8), true);
  assert.equal(H.skinMatrixMatches(SK_IDENTITY.slice(), 0), true);
  assert.equal(H.skinMatrixMatches(skTxMatrix(0.8), 0.8), true);
  assert.equal(H.skinDrawMatches(skValidDraw({ tx: 0 }), 0, 1, -1), true);
  assert.equal(H.skinDrawMatches(skValidDraw({ tx: 0.8 }), 0.8, 1, -1), true);
  assert.equal(H.skinDrawMatches(
    skValidDraw({ tx: 0, lastOpacity: 0.5, lastAlphaCutoff: 0.5 }),
    0, 0.5, 0.5), true);
  assert.equal(H.skinDrawMatches(
    skValidDraw({ tx: 0, lastOpacity: 0.25, lastAlphaCutoff: 0.5 }),
    0, 0.25, 0.5), true);
  assert.equal(H.skinDrawMatches(
    skValidDraw({ tx: 0, lastHasSkin: 1 }), 0, 1, -1), true);
});

test("actual skinStateReady rejects bad state (old all-ones weights bug)", () => {
  const H = loadProbeSkinHelpers();
  const c = { skinnedExpectPose: true, skinnedExpectMixer: true };
  const rejects = (mut, label) => {
    const snap = skValidState({ paletteTx: 0.8, animation: "pose", mixer: true });
    mut(snap.skinState);
    assert.equal(H.skinStateReady(snap, c, 0.8), false, label);
  };
  rejects((st) => { st.object.weights = [1, 1, 1, 1]; }, "old weights-all-1 bug");
  rejects((st) => { st.object.weights = [0, 1, 0, 0]; }, "wrong weight index");
  rejects((st) => { st.object.joints = [1, 0, 0, 0]; }, "wrong joints");
  rejects((st) => { st.object.jointsLength = 2; }, "missing joints");
  rejects((st) => { st.object.castShadow = false; }, "castShadow false");
  rejects((st) => { st.object = null; }, "missing object");
  rejects((st) => { st.palette = null; st.paletteLength = 0; }, "missing palette");
  rejects((st) => { st.palette[7] = NaN; }, "NaN in palette");
  rejects((st) => { st.palette = skTxMatrix(0); }, "palette wrong translation");
  rejects((st) => { st.rootTransform = skTxMatrix(0.8); }, "non-identity root");
  rejects((st) => { st.animation = ""; }, "wrong animation");
  rejects((st) => { st.hasMixer = false; }, "missing mixer");
  rejects((st) => { st.records = 2; }, "wrong record count");
  // Fail closed: the published animation API must be observed with real
  // capabilities and must match the skin record's animationApi.
  rejects((st) => { st.animationApiCapabilities = false; }, "animation API capabilities absent");
  rejects((st) => { st.animationApiMatchesRecord = false; }, "animation API differs from record");
  const noApiCaps = skValidState({ paletteTx: 0.8, animation: "pose", mixer: true });
  delete noApiCaps.skinState.animationApiCapabilities;
  assert.equal(H.skinStateReady(noApiCaps, c, 0.8), false,
    "missing animationApiCapabilities field");
  const noApiMatch = skValidState({ paletteTx: 0.8, animation: "pose", mixer: true });
  delete noApiMatch.skinState.animationApiMatchesRecord;
  assert.equal(H.skinStateReady(noApiMatch, c, 0.8), false,
    "missing animationApiMatchesRecord field");
  // NaN tx must never pass the finite tx guard.
  assert.equal(H.skinStateReady(skValidState(), {}, NaN), false);
  assert.equal(H.skinMatrixMatches(SK_IDENTITY.slice(), NaN), false);
});

test("actual skinDrawMatches pins the real observer field names and values", () => {
  const H = loadProbeSkinHelpers();
  const rejects = (draw, tx, op, cut, label) =>
    assert.equal(H.skinDrawMatches(draw, tx, op, cut), false, label);
  rejects(skValidDraw({ lastHasSkin: false, tx: 0 }), 0, 1, -1, "hasSkin false");
  // Invented/renamed fields must NOT satisfy the actual predicate.
  rejects({ hasSkin: true, draws: 1, lastProgramId: 7,
    lastPalette0: SK_IDENTITY.slice(), lastModelMatrix: SK_IDENTITY.slice(),
    lastOpacity: 1, lastAlphaCutoff: -1, palette: SK_IDENTITY.slice(),
    modelMatrix: SK_IDENTITY.slice(), drawOpacity: 1,
    drawAlphaCutoff: -1 }, 0, 1, -1, "renamed fields");
  rejects(skValidDraw({ draws: 0, tx: 0 }), 0, 1, -1, "zero draws");
  rejects(skValidDraw({ lastProgramId: 0, tx: 0 }), 0, 1, -1, "zero program id");
  rejects(skValidDraw({ lastProgramId: null, tx: 0 }), 0, 1, -1, "null program id");
  rejects(skValidDraw({ lastPalette0: null, tx: 0 }), 0, 1, -1, "null palette");
  rejects(skValidDraw({ lastPalette0: skTxMatrix(0.8), tx: 0 }), 0, 1, -1,
    "wrong palette");
  rejects(skValidDraw({ lastModelMatrix: skTxMatrix(0.5), tx: 0 }), 0, 1, -1,
    "wrong model matrix");
  rejects(skValidDraw({ tx: 0.8 }), 0.8, 0.5, -1, "wrong opacity");
  rejects(skValidDraw({ tx: 0.8 }), 0.8, 1, 0.5, "wrong cutoff");
  rejects(null, 0, 1, -1, "null draw");
  rejects(skValidDraw({ tx: 0 }), NaN, 1, -1, "NaN tx");
});

test("actual addSkinnedShadowCases registers 16 ordered cases with wiring", () => {
  const CASES = loadProbeSkinnedShadowCases();
  assert.equal(CASES.length, 16);
  const tails = ["empty", "ref-rest", "ref-pose", "rest", "pose",
    "mask-survive", "mask-discard", "live"];
  const map = {};
  CASES.forEach((c, i) => {
    const pfx = (i < 8) ? "gl-sk-" : "wg-sk-";
    assert.equal(c.name, pfx + tails[i % 8], "ordered name at " + i);
    assert.equal(c.webgpu, i >= 8);
    assert.equal(c.skinnedShadowGroup, true);
    map[c.name] = c;
  });
  ["gl-sk-", "wg-sk-"].forEach((pfx) => {
    ["pose", "mask-survive", "mask-discard"].forEach((tail) => {
      assert.equal(map[pfx + tail].skinnedExpectPose, true, pfx + tail + " pose");
      assert.equal(map[pfx + tail].skinnedExpectMixer, true, pfx + tail + " mixer");
    });
    ["empty", "ref-rest", "ref-pose", "rest"].forEach((tail) => {
      assert.equal(map[pfx + tail].skinnedExpectPose, undefined, pfx + tail);
      assert.equal(map[pfx + tail].skinnedExpectMixer, undefined, pfx + tail);
    });
    assert.equal(map[pfx + "live"].skinnedLive, true);
    assert.equal(map[pfx + "live"].skinnedExpectMixer, true);
    assert.equal(map[pfx + "live"].skinnedExpectPose, undefined);
    assert.equal(map[pfx + "mask-survive"].skinnedMaskOpacity, 0.5);
    assert.equal(map[pfx + "mask-survive"].skinnedMaskCutoff, 0.5);
    assert.equal(map[pfx + "mask-discard"].skinnedMaskOpacity, 0.25);
    assert.equal(map[pfx + "mask-discard"].skinnedMaskCutoff, 0.5);
    ["rest", "pose", "mask-survive", "mask-discard", "live"].forEach((tail) => {
      assert.equal(map[pfx + tail].model.id, "skin-caster");
      assert.equal(map[pfx + tail].model.castShadow, true);
      assert.equal(map[pfx + tail].skinnedGlb, tail === "rest" ? "rest" : "pose");
    });
    assert.equal(map[pfx + "rest"].same, pfx + "ref-rest");
    assert.equal(map[pfx + "rest"].differs, pfx + "empty");
    assert.equal(map[pfx + "pose"].same, pfx + "ref-pose");
    assert.equal(map[pfx + "pose"].differs, pfx + "empty");
    assert.equal(map[pfx + "mask-survive"].same, pfx + "ref-pose");
    assert.equal(map[pfx + "mask-discard"].same, pfx + "empty");
    assert.equal(map[pfx + "mask-discard"].differs, pfx + "ref-pose");
    assert.equal(map[pfx + "live"].same, pfx + "ref-rest");
  });
});
