// Code generated by danmuji — DO NOT EDIT.

// CRDT convergence scenarios. Compiled by danmuji into
// crdt/convergence_scenarios_danmuji_test.go.
//
// Rebuild after editing:
//     danmuji build crdt/convergence_scenarios.dmj

package crdt

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"testing"
	"testing/quick"
)

func danmujiDeepEqual(expected, actual interface{}) bool {
	if reflect.DeepEqual(expected, actual) {
		return true
	}

	expectedValue := reflect.ValueOf(expected)
	actualValue := reflect.ValueOf(actual)
	if !expectedValue.IsValid() || !actualValue.IsValid() {
		return false
	}
	if !danmujiIsNumericKind(expectedValue.Kind()) || !danmujiIsNumericKind(actualValue.Kind()) {
		return false
	}

	return danmujiNumericEqual(expectedValue, actualValue)
}

func danmujiNumericEqual(expected, actual reflect.Value) bool {
	switch {
	case danmujiIsSignedKind(expected.Kind()):
		expectedInt := expected.Int()
		switch {
		case danmujiIsSignedKind(actual.Kind()):
			return expectedInt == actual.Int()
		case danmujiIsUnsignedKind(actual.Kind()):
			return expectedInt >= 0 && uint64(expectedInt) == actual.Uint()
		case danmujiIsFloatKind(actual.Kind()):
			return float64(expectedInt) == actual.Float()
		}
	case danmujiIsUnsignedKind(expected.Kind()):
		expectedUint := expected.Uint()
		switch {
		case danmujiIsSignedKind(actual.Kind()):
			actualInt := actual.Int()
			return actualInt >= 0 && expectedUint == uint64(actualInt)
		case danmujiIsUnsignedKind(actual.Kind()):
			return expectedUint == actual.Uint()
		case danmujiIsFloatKind(actual.Kind()):
			return float64(expectedUint) == actual.Float()
		}
	case danmujiIsFloatKind(expected.Kind()):
		expectedFloat := expected.Float()
		switch {
		case danmujiIsSignedKind(actual.Kind()):
			return expectedFloat == float64(actual.Int())
		case danmujiIsUnsignedKind(actual.Kind()):
			return expectedFloat == float64(actual.Uint())
		case danmujiIsFloatKind(actual.Kind()):
			return expectedFloat == actual.Float()
		}
	}

	return false
}

func danmujiIsNumericKind(kind reflect.Kind) bool {
	return danmujiIsSignedKind(kind) || danmujiIsUnsignedKind(kind) || danmujiIsFloatKind(kind)
}

func danmujiIsSignedKind(kind reflect.Kind) bool {
	switch kind {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return true
	}
	return false
}

func danmujiIsUnsignedKind(kind reflect.Kind) bool {
	switch kind {
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return true
	}
	return false
}

func danmujiIsFloatKind(kind reflect.Kind) bool {
	switch kind {
	case reflect.Float32, reflect.Float64:
		return true
	}
	return false
}

func danmujiContains(actual, expected interface{}) (found bool) {
	if actual == nil || expected == nil {
		return false
	}
	defer func() {
		if recover() != nil {
			found = false
		}
	}()

	if s, ok := actual.(string); ok {
		needle, ok := expected.(string)
		if !ok {
			return false
		}
		return strings.Contains(s, needle)
	}

	rv := reflect.ValueOf(actual)
	switch rv.Kind() {
	case reflect.Array, reflect.Slice:
		for i := 0; i < rv.Len(); i++ {
			if danmujiDeepEqual(rv.Index(i).Interface(), expected) {
				return true
			}
		}
	case reflect.Map:
		if rv.MapIndex(reflect.ValueOf(expected)).IsValid() {
			return true
		}
	}
	return false
}

type danmujiMatcher struct {
	kind     string
	expected interface{}
}

func danmujiMatchContains(expected interface{}) danmujiMatcher {
	return danmujiMatcher{kind: "contains", expected: expected}
}

func danmujiMatchNil() danmujiMatcher {
	return danmujiMatcher{kind: "nil"}
}

func danmujiMatchNotNil() danmujiMatcher {
	return danmujiMatcher{kind: "not_nil"}
}

func danmujiMatches(expected map[string]interface{}, actual interface{}) bool {
	ok, _ := danmujiPartialMatch(expected, actual)
	return ok
}

func danmujiPartialMatch(expected map[string]interface{}, actual interface{}) (bool, string) {
	actualValue := reflect.ValueOf(actual)
	if !actualValue.IsValid() {
		return false, "actual value is nil"
	}
	for actualValue.Kind() == reflect.Pointer {
		if actualValue.IsNil() {
			return false, "actual value is nil"
		}
		actualValue = actualValue.Elem()
	}

	keys := make([]string, 0, len(expected))
	for key := range expected {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		fieldValue, ok := danmujiLookupMatchField(actualValue, key)
		if !ok {
			return false, fmt.Sprintf("missing field %q", key)
		}
		if ok, detail := danmujiMatchValue(expected[key], fieldValue.Interface()); !ok {
			return false, fmt.Sprintf("%s: %s", key, detail)
		}
	}

	return true, ""
}

func danmujiLookupMatchField(actual reflect.Value, key string) (reflect.Value, bool) {
	switch actual.Kind() {
	case reflect.Struct:
		field := actual.FieldByName(key)
		if !field.IsValid() {
			return reflect.Value{}, false
		}
		return field, true
	case reflect.Map:
		if actual.Type().Key().Kind() != reflect.String {
			return reflect.Value{}, false
		}
		field := actual.MapIndex(reflect.ValueOf(key))
		if !field.IsValid() {
			return reflect.Value{}, false
		}
		return field, true
	}
	return reflect.Value{}, false
}

func danmujiMatchValue(expected, actual interface{}) (bool, string) {
	switch spec := expected.(type) {
	case danmujiMatcher:
		switch spec.kind {
		case "contains":
			if danmujiContains(actual, spec.expected) {
				return true, ""
			}
			return false, fmt.Sprintf("expected %v to contain %v", actual, spec.expected)
		case "nil":
			if danmujiIsNilish(actual) {
				return true, ""
			}
			return false, fmt.Sprintf("expected nil, got %v", actual)
		case "not_nil":
			if !danmujiIsNilish(actual) {
				return true, ""
			}
			return false, "expected non-nil value"
		}
	}

	if danmujiDeepEqual(expected, actual) {
		return true, ""
	}
	return false, fmt.Sprintf("expected %v, got %v", expected, actual)
}

func danmujiIsNilish(value interface{}) bool {
	if value == nil {
		return true
	}
	rv := reflect.ValueOf(value)
	switch rv.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return rv.IsNil()
	}
	return false
}

func danmujiUnorderedEqual(expected, actual interface{}) bool {
	ok, _ := danmujiUnorderedEqualDetail(expected, actual)
	return ok
}

func danmujiUnorderedEqualDetail(expected, actual interface{}) (bool, string) {
	expectedValue := reflect.ValueOf(expected)
	actualValue := reflect.ValueOf(actual)
	if !expectedValue.IsValid() || !actualValue.IsValid() {
		if !expectedValue.IsValid() && !actualValue.IsValid() {
			return true, ""
		}
		return false, "one side is nil"
	}

	if (expectedValue.Kind() != reflect.Slice && expectedValue.Kind() != reflect.Array) ||
		(actualValue.Kind() != reflect.Slice && actualValue.Kind() != reflect.Array) {
		return false, "unordered_equal requires slices or arrays"
	}

	if expectedValue.Len() != actualValue.Len() {
		return false, fmt.Sprintf("length mismatch: expected %d, got %d", expectedValue.Len(), actualValue.Len())
	}

	used := make([]bool, actualValue.Len())
	for i := 0; i < expectedValue.Len(); i++ {
		expectedElem := expectedValue.Index(i).Interface()
		found := false
		for j := 0; j < actualValue.Len(); j++ {
			if used[j] {
				continue
			}
			if danmujiDeepEqual(expectedElem, actualValue.Index(j).Interface()) {
				used[j] = true
				found = true
				break
			}
		}
		if !found {
			return false, fmt.Sprintf("missing element %v in actual value %v", expectedElem, actual)
		}
	}

	return true, ""
}
func TestPartitionedListConvergenceScenarios(t *testing.T) {
//line crdt/convergence_scenarios.dmj:15
	t.Parallel()
	type PartitionSizeScenario struct {
		name        interface{}
		left_count  interface{}
		right_count interface{}
	}
	scenarios := []PartitionSizeScenario{
		{name: "small symmetric partition", left_count: 3, right_count: 3},
		{name: "left-heavy partition", left_count: 17, right_count: 4},
		{name: "right-heavy partition", left_count: 4, right_count: 17},
	}
	for _, scenario := range scenarios {
		_scenarioName := fmt.Sprintf("%v", scenario.name)
		t.Run(_scenarioName, func(t *testing.T) {
			t.Parallel()
			left_count := scenario.left_count
			_ = left_count
			right_count := scenario.right_count
			_ = right_count
			base := NewDoc()
			items, err := base.MakeList(Root, "items")
			if err != nil {
				t.Fatal(err)
			}
			if _, err := base.Commit("seed list"); err != nil {
				t.Fatal(err)
			}
			left := forkWithActor(t, base, 31)
			right := forkWithActor(t, base, 32)
			for i := 0; i < scenario.left_count.(int); i++ {
				if err := left.InsertAt(items, uint64(i), StringValue(fmt.Sprintf("left-%02d", i))); err != nil {
					t.Fatal(err)
				}
			}
			for i := 0; i < scenario.right_count.(int); i++ {
				if err := right.InsertAt(items, uint64(i), StringValue(fmt.Sprintf("right-%02d", i))); err != nil {
					t.Fatal(err)
				}
			}
			if _, err := left.Commit("left partition"); err != nil {
				t.Fatal(err)
			}
			if _, err := right.Commit("right partition"); err != nil {
				t.Fatal(err)
			}
			if err := left.Merge(right); err != nil {
				t.Fatal(err)
			}
			if err := right.Merge(left); err != nil {
				t.Fatal(err)
			}
			leftValues := listStrings(t, left, items)
			rightValues := listStrings(t, right, items)
			//line crdt/convergence_scenarios.dmj:59
			t.Run("converges to a deterministic order", func(t *testing.T) {
				if strings.Join(leftValues, "|") != strings.Join(rightValues, "|") {
					t.Fatalf("list order diverged: left=%#v right=%#v", leftValues, rightValues)
				}
			})
			//line crdt/convergence_scenarios.dmj:65
			t.Run("keeps every concurrent insert", func(t *testing.T) {
				want := scenario.left_count.(int) + scenario.right_count.(int)
				if len(leftValues) != want {
					t.Fatalf("list len = %d, want %d", len(leftValues), want)
				}
			})
		})
	}

	if err := quick.Check(func(leftRaw uint8, rightRaw uint8) bool {
		leftCount := int(leftRaw%24) + 1
		rightCount := int(rightRaw%24) + 1
		base := NewDoc()
		items, err := base.MakeList(Root, "items")
		if err != nil {
			return false
		}
		if _, err := base.Commit("seed list"); err != nil {
			return false
		}
		left := forkWithActor(t, base, 41)
		right := forkWithActor(t, base, 42)
		for i := 0; i < leftCount; i++ {
			if err := left.InsertAt(items, uint64(i), StringValue(fmt.Sprintf("left-%02d", i))); err != nil {
				return false
			}
		}
		for i := 0; i < rightCount; i++ {
			if err := right.InsertAt(items, uint64(i), StringValue(fmt.Sprintf("right-%02d", i))); err != nil {
				return false
			}
		}
		if _, err := left.Commit("left partition"); err != nil {
			return false
		}
		if _, err := right.Commit("right partition"); err != nil {
			return false
		}
		if err := left.Merge(right); err != nil {
			return false
		}
		if err := right.Merge(left); err != nil {
			return false
		}
		leftValues := listStrings(t, left, items)
		rightValues := listStrings(t, right, items)
		if strings.Join(leftValues, "|") != strings.Join(rightValues, "|") {
			return false
		}
		return len(leftValues) == leftCount+rightCount
		return true
	}, &quick.Config{MaxCount: 60}); err != nil {
		t.Fatalf("danmuji:73 property %s failed: %v", "bounded two actor list inserts converge", err)
	}

}

func FuzzDanmujiLoadDocumentNeverPanics(f *testing.F) {
	f.Add([]byte{})
	f.Add([]byte("not a gosx crdt document"))
	f.Fuzz(func(t *testing.T, payload []byte) {
		if len(payload) > 65536 {
			return
		}
		_, _ = Load(payload)
	})
}
