package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInitPreflightsEveryOutput(t *testing.T) {
	for _, name := range []string{"public/styles.css", "modules/modules.go", "go.sum"} {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			target := filepath.Join(dir, name)
			if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(target, []byte("caller content"), 0644); err != nil {
				t.Fatal(err)
			}
			files, err := scaffoldFilesForTemplate("example.com/app", "app")
			if err != nil {
				t.Fatal(err)
			}
			_, err = createScaffold(dir, "example.com/app", files, func(string) error {
				t.Fatal("tidy ran despite a pre-existing conflict")
				return nil
			})
			if err == nil || !strings.Contains(err.Error(), name) {
				t.Fatalf("wanted conflict for %s, got %v", name, err)
			}
			if got := readFile(t, target); got != "caller content" {
				t.Fatalf("caller file changed: %q", got)
			}
			if _, err := os.Stat(filepath.Join(dir, "go.mod")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("preflight wrote go.mod: %v", err)
			}
		})
	}
}

func TestInitRejectsSymlinkParentsAndDanglingTargets(t *testing.T) {
	for _, target := range []string{"app", "modules", "public/styles.css", "go.sum"} {
		t.Run(target, func(t *testing.T) {
			dir := t.TempDir()
			outside := t.TempDir()
			name := filepath.Join(dir, target)
			if err := os.MkdirAll(filepath.Dir(name), 0755); err != nil {
				t.Fatal(err)
			}
			linkTarget := outside
			if strings.Contains(target, ".") {
				linkTarget = filepath.Join(outside, "absent")
			}
			if err := os.Symlink(linkTarget, name); err != nil {
				t.Skipf("symlinks unavailable: %v", err)
			}
			if err := RunInit(dir, "example.com/app", "app"); err == nil {
				t.Fatal("init accepted a symlink")
			}
			entries, err := os.ReadDir(outside)
			if err != nil || len(entries) != 0 {
				t.Fatalf("init wrote outside destination: %v, %v", entries, err)
			}
			if _, err := os.Stat(filepath.Join(dir, "go.mod")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("init wrote go.mod before rejecting symlink: %v", err)
			}
		})
	}
}

func TestInitRejectsSymlinkRoot(t *testing.T) {
	outside := t.TempDir()
	link := filepath.Join(t.TempDir(), "project")
	if err := os.Symlink(outside, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := RunInit(link, "example.com/app", "app"); err == nil {
		t.Fatal("init accepted a symlink root")
	}
	entries, err := os.ReadDir(outside)
	if err != nil || len(entries) != 0 {
		t.Fatalf("init wrote through a symlink root: %v, %v", entries, err)
	}
}

func TestInitTidyRunsOnlyInStaging(t *testing.T) {
	for _, fail := range []bool{false, true} {
		t.Run(map[bool]string{false: "success", true: "failure"}[fail], func(t *testing.T) {
			dir := t.TempDir()
			files, err := scaffoldFilesForTemplate("example.com/app", "app")
			if err != nil {
				t.Fatal(err)
			}
			originalMod := files[0].Contents
			var stageDir string
			tidyErr, err := createScaffold(dir, "example.com/app", files, func(stage string) error {
				stageDir = stage
				if stage == dir {
					t.Fatal("tidy ran in the destination")
				}
				if _, err := os.Stat(filepath.Join(dir, "go.mod")); !errors.Is(err, os.ErrNotExist) {
					t.Fatalf("files published before tidy completed: %v", err)
				}
				modules := readFile(t, filepath.Join(stage, "modules/modules.go"))
				if !strings.Contains(modules, `// Code generated by gosx.`) || !strings.Contains(modules, `"example.com/app/app/stack"`) {
					t.Fatalf("modules not generated before tidy: %s", modules)
				}
				for _, name := range []string{"go.mod", "go.sum", "unexpected.txt"} {
					if err := os.WriteFile(filepath.Join(stage, name), []byte("tidy output"), 0644); err != nil {
						t.Fatal(err)
					}
				}
				if fail {
					return errors.New("offline")
				}
				return nil
			})
			if err != nil || (tidyErr != nil) != fail {
				t.Fatalf("createScaffold: tidy=%v, err=%v", tidyErr, err)
			}
			want := "tidy output"
			if fail {
				want = originalMod
			}
			if got := readFile(t, filepath.Join(dir, "go.mod")); got != want {
				t.Fatalf("wrong go.mod after tidy: %q", got)
			}
			_, sumErr := os.Stat(filepath.Join(dir, "go.sum"))
			if fail && !errors.Is(sumErr, os.ErrNotExist) || !fail && sumErr != nil {
				t.Fatalf("wrong go.sum after tidy: %v", sumErr)
			}
			if _, err := os.Stat(filepath.Join(dir, "unexpected.txt")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("copied unexpected tidy output: %v", err)
			}
			if _, err := os.Stat(stageDir); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("staging directory was not cleaned: %v", err)
			}
		})
	}
}

func TestInitPreservesExistingRouteRegistration(t *testing.T) {
	dir := t.TempDir()
	name := filepath.Join(dir, "app", "custom", "page.server.go")
	if err := os.MkdirAll(filepath.Dir(name), 0755); err != nil {
		t.Fatal(err)
	}
	const content = "package custom\n// caller-owned route module\n"
	if err := os.WriteFile(name, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	files, err := scaffoldFilesForTemplate("example.com/app", "app")
	if err != nil {
		t.Fatal(err)
	}
	tidyErr, err := createScaffold(dir, "example.com/app", files, func(string) error {
		t.Fatal("tidy must not try to download an existing local route absent from staging")
		return nil
	})
	if err != nil || tidyErr == nil {
		t.Fatalf("expected complete scaffold with a tidy reminder: tidy=%v err=%v", tidyErr, err)
	}
	if got := readFile(t, name); got != content {
		t.Fatalf("existing route changed: %q", got)
	}
	modules := readFile(t, filepath.Join(dir, "modules", "modules.go"))
	if !strings.Contains(modules, `"example.com/app/app/custom"`) || !strings.Contains(modules, `"example.com/app/app/stack"`) {
		t.Fatalf("missing existing or scaffold route registration: %s", modules)
	}
}

func TestScaffoldPublicationPreservesConcurrentFiles(t *testing.T) {
	for _, kind := range []string{"file", "symlink"} {
		t.Run(kind, func(t *testing.T) {
			dir := t.TempDir()
			root := openScaffoldTestRoot(t, dir)
			err := publishScaffold(root, []scaffoldFile{{"first", "framework"}, {"last", "framework"}}, func(i int) error {
				if i != 1 {
					return nil
				}
				if kind == "symlink" {
					if err := os.Symlink("caller-target", filepath.Join(dir, "last")); err != nil {
						t.Skipf("symlinks unavailable: %v", err)
					}
					return nil
				}
				return os.WriteFile(filepath.Join(dir, "last"), []byte("caller"), 0644)
			})
			if err == nil {
				t.Fatal("publication overwrote a concurrently created destination")
			}
			if _, err := os.Stat(filepath.Join(dir, "first")); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("did not roll back earlier publication: %v", err)
			}
			if kind == "file" {
				if got := readFile(t, filepath.Join(dir, "last")); got != "caller" {
					t.Fatalf("overwrote concurrent file: %q", got)
				}
			} else if link, err := os.Readlink(filepath.Join(dir, "last")); err != nil || link != "caller-target" {
				t.Fatalf("overwrote concurrent symlink: %s, %v", link, err)
			}
			assertNoScaffoldStages(t, dir)
		})
	}
}

func TestScaffoldRollbackPreservesCallerEdits(t *testing.T) {
	for _, replacement := range []bool{false, true} {
		t.Run(map[bool]string{false: "in-place edit", true: "replacement with same bytes"}[replacement], func(t *testing.T) {
			dir := t.TempDir()
			root := openScaffoldTestRoot(t, dir)
			content := "edited"
			if replacement {
				content = "framework"
			}
			err := publishScaffold(root, []scaffoldFile{{"first", "framework"}, {"last", "framework"}}, func(i int) error {
				if i != 1 {
					return nil
				}
				name := filepath.Join(dir, "first")
				if replacement {
					if err := os.Remove(name); err != nil {
						return err
					}
				}
				if err := os.WriteFile(name, []byte(content), 0644); err != nil {
					return err
				}
				return errors.New("injected publication failure")
			})
			if err == nil || !strings.Contains(err.Error(), "preserving first") {
				t.Fatalf("missing retained-file diagnostic: %v", err)
			}
			if got := readFile(t, filepath.Join(dir, "first")); got != content {
				t.Fatalf("rollback lost caller edit: %q", got)
			}
			assertNoScaffoldStages(t, dir)
		})
	}
}

func TestScaffoldRejectsParentSwapDuringPublication(t *testing.T) {
	dir := t.TempDir()
	root := openScaffoldTestRoot(t, dir)
	err := publishScaffold(root, []scaffoldFile{{"app/page.gsx", "framework"}}, func(int) error {
		if err := os.Rename(filepath.Join(dir, "app"), filepath.Join(dir, "original")); err != nil {
			return err
		}
		return os.Mkdir(filepath.Join(dir, "app"), 0755)
	})
	if err == nil || !strings.Contains(err.Error(), "changed during init") {
		t.Fatalf("parent swap not rejected: %v", err)
	}
	for _, parent := range []string{"app", "original"} {
		if _, err := os.Stat(filepath.Join(dir, parent, "page.gsx")); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("published into swapped parent %s: %v", parent, err)
		}
	}
	assertNoScaffoldStages(t, dir)
}

func TestScaffoldRejectsInvalidPlanBeforeWriting(t *testing.T) {
	for _, paths := range [][]string{{"../outside"}, {"."}, {"/absolute"}, {"app\\escape"}, {"a", "a"}, {"a/b", "a"}} {
		t.Run(strings.Join(paths, ","), func(t *testing.T) {
			dir := t.TempDir()
			root := openScaffoldTestRoot(t, dir)
			var files []scaffoldFile
			for _, name := range paths {
				files = append(files, scaffoldFile{name, "content"})
			}
			if err := publishScaffold(root, files, nil); err == nil {
				t.Fatal("invalid plan accepted")
			}
			entries, err := os.ReadDir(dir)
			if err != nil || len(entries) != 0 {
				t.Fatalf("invalid plan wrote files: %v, %v", entries, err)
			}
		})
	}
}

func openScaffoldTestRoot(t *testing.T, dir string) *os.Root {
	t.Helper()
	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { root.Close() })
	return root
}

func assertNoScaffoldStages(t *testing.T, dir string) {
	t.Helper()
	if err := filepath.WalkDir(dir, func(name string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if strings.HasPrefix(entry.Name(), ".gosx-init-") {
			t.Errorf("staging file remains: %s", name)
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
}
