package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

func syncModulesPackage(projectDir string) error {
	absProjectDir, err := filepath.Abs(projectDir)
	if err != nil {
		return fmt.Errorf("resolve project dir: %w", err)
	}
	projectDir = absProjectDir

	moduleRoot, modulePath, err := moduleInfo(projectDir)
	if err != nil {
		return err
	}
	imports, err := discoverModuleImports(projectDir, moduleRoot, modulePath)
	if err != nil {
		return err
	}

	modulesDir := filepath.Join(projectDir, "modules")
	if err := os.MkdirAll(modulesDir, 0755); err != nil {
		return fmt.Errorf("create modules dir: %w", err)
	}
	path := filepath.Join(modulesDir, "modules.go")
	if err := os.WriteFile(path, []byte(renderModulesPackage(imports)), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func moduleInfo(projectDir string) (string, string, error) {
	cmd := exec.Command("go", "env", "GOMOD")
	cmd.Dir = projectDir
	out, err := cmd.Output()
	if err != nil {
		return "", "", fmt.Errorf("resolve go.mod: %w", err)
	}
	goModPath := strings.TrimSpace(string(out))
	if goModPath == "" || goModPath == os.DevNull {
		return "", "", fmt.Errorf("go.mod not found for %s", projectDir)
	}
	file, err := os.Open(goModPath)
	if err != nil {
		return "", "", fmt.Errorf("read go.mod: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "module ") {
			continue
		}
		module := strings.TrimSpace(strings.TrimPrefix(line, "module "))
		if module == "" {
			break
		}
		return filepath.Dir(goModPath), module, nil
	}
	if err := scanner.Err(); err != nil {
		return "", "", fmt.Errorf("scan go.mod: %w", err)
	}
	return "", "", fmt.Errorf("module path not found in go.mod")
}

func discoverModuleImports(projectDir, moduleRoot, modulePath string) ([]string, error) {
	appDir := filepath.Join(projectDir, "app")
	info, err := os.Stat(appDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat app dir: %w", err)
	}
	if !info.IsDir() {
		return nil, nil
	}

	importSet := map[string]struct{}{}
	err = filepath.Walk(appDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			name := info.Name()
			if name != "." && strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(info.Name(), ".server.go") {
			return nil
		}
		dir := filepath.Dir(path)
		rel, err := filepath.Rel(moduleRoot, dir)
		if err != nil {
			return fmt.Errorf("relative import path for %s: %w", dir, err)
		}
		importPath := modulePath
		if rel != "." && rel != "" {
			importPath += "/" + filepath.ToSlash(rel)
		}
		importSet[importPath] = struct{}{}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("scan app modules: %w", err)
	}

	imports := make([]string, 0, len(importSet))
	for importPath := range importSet {
		imports = append(imports, importPath)
	}
	sort.Strings(imports)
	return imports, nil
}

func renderModulesPackage(imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by gosx. DO NOT EDIT.\n")
	b.WriteString("package modules\n")
	if len(imports) == 0 {
		b.WriteByte('\n')
		return b.String()
	}
	b.WriteString("\nimport (\n")
	for _, importPath := range imports {
		fmt.Fprintf(&b, "\t_ %q\n", importPath)
	}
	b.WriteString(")\n")
	return b.String()
}
