apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gosx-demo-redirect
  namespace: draco-quest
spec:
  redirectRegex:
    regex: ^https?://gosx-demo\.m31labs\.dev/(.*)
    replacement: https://gosx.m31labs.dev/$1
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gosx-demo
  namespace: draco-quest
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    traefik.ingress.kubernetes.io/router.middlewares: draco-quest-gosx-demo-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "20"
spec:
  ingressClassName: traefik
  rules:
    - host: gosx-demo.m31labs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gosx-docs
                port:
                  name: http
  tls:
    - hosts:
        - gosx-demo.m31labs.dev
      secretName: gosx-demo-tls
