package server

import (
	"path"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx"
)

// FontSource describes one font file used by Font.
type FontSource struct {
	Src    string
	Type   string
	Format string
}

// FontProps configures a server-rendered @font-face helper.
type FontProps struct {
	Family      string
	Src         string
	Sources     []FontSource
	Type        string
	Format      string
	Weight      string
	Style       string
	Display     string
	CrossOrigin string
	NoPreload   bool
}

// Font renders preload metadata plus an @font-face declaration. The default
// font-display is optional so text can render immediately without a swap flash.
func Font(props FontProps, args ...any) gosx.Node {
	family := strings.TrimSpace(props.Family)
	sources := normalizeFontSources(props)
	if family == "" || len(sources) == 0 {
		return gosx.Text("")
	}

	nodes := []gosx.Node{}
	if !props.NoPreload {
		preload := sources[0]
		crossOrigin := strings.TrimSpace(props.CrossOrigin)
		if crossOrigin == "" {
			crossOrigin = "anonymous"
		}
		attrs := []any{
			gosx.Attrs(
				gosx.Attr("rel", "preload"),
				gosx.Attr("as", "font"),
				gosx.Attr("href", preload.Src),
				gosx.Attr("type", preload.Type),
				gosx.Attr("crossorigin", crossOrigin),
			),
		}
		attrs = append(attrs, args...)
		nodes = append(nodes, gosx.El("link", attrs...))
	}

	nodes = append(nodes, gosx.RawHTML(`<style data-gosx-font>`+FontFaceCSS(props)+`</style>`))
	return gosx.Fragment(nodes...)
}

// FontFaceCSS returns the @font-face CSS generated by Font.
func FontFaceCSS(props FontProps) string {
	family := strings.TrimSpace(props.Family)
	sources := normalizeFontSources(props)
	if family == "" || len(sources) == 0 {
		return ""
	}

	display := sanitizeCSSDescriptor(props.Display, "optional")
	weight := sanitizeCSSDescriptor(props.Weight, "400")
	style := sanitizeCSSDescriptor(props.Style, "normal")

	srcParts := make([]string, 0, len(sources))
	for _, source := range sources {
		part := "url(" + cssString(source.Src) + ")"
		if source.Format != "" {
			part += " format(" + cssString(source.Format) + ")"
		}
		srcParts = append(srcParts, part)
	}

	var b strings.Builder
	b.Grow(128 + len(family) + len(srcParts)*48)
	b.WriteString("@font-face{font-family:")
	b.WriteString(cssString(family))
	b.WriteString(";src:")
	b.WriteString(strings.Join(srcParts, ","))
	b.WriteString(";font-style:")
	b.WriteString(style)
	b.WriteString(";font-weight:")
	b.WriteString(weight)
	b.WriteString(";font-display:")
	b.WriteString(display)
	b.WriteString(";}")
	return b.String()
}

func normalizeFontSources(props FontProps) []FontSource {
	sources := append([]FontSource(nil), props.Sources...)
	if strings.TrimSpace(props.Src) != "" {
		sources = append([]FontSource{{
			Src:    props.Src,
			Type:   props.Type,
			Format: props.Format,
		}}, sources...)
	}

	out := make([]FontSource, 0, len(sources))
	for _, source := range sources {
		source.Src = AssetURL(source.Src)
		if strings.TrimSpace(source.Src) == "" {
			continue
		}
		source.Type = strings.TrimSpace(source.Type)
		source.Format = strings.TrimSpace(source.Format)
		if source.Type == "" {
			source.Type = inferFontType(source.Src)
		}
		if source.Format == "" {
			source.Format = inferFontFormat(source.Src, source.Type)
		}
		out = append(out, source)
	}
	return out
}

func inferFontType(src string) string {
	switch strings.ToLower(path.Ext(src)) {
	case ".woff2":
		return "font/woff2"
	case ".woff":
		return "font/woff"
	case ".ttf":
		return "font/ttf"
	case ".otf":
		return "font/otf"
	default:
		return "font/woff2"
	}
}

func inferFontFormat(src, typ string) string {
	switch strings.TrimSpace(strings.ToLower(typ)) {
	case "font/woff2":
		return "woff2"
	case "font/woff":
		return "woff"
	case "font/ttf":
		return "truetype"
	case "font/otf":
		return "opentype"
	}
	switch strings.ToLower(path.Ext(src)) {
	case ".woff2":
		return "woff2"
	case ".woff":
		return "woff"
	case ".ttf":
		return "truetype"
	case ".otf":
		return "opentype"
	default:
		return ""
	}
}

func sanitizeCSSDescriptor(value, fallback string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return fallback
	}
	value = strings.NewReplacer(";", "", "{", "", "}", "", "\n", " ", "\r", " ").Replace(value)
	return strings.TrimSpace(value)
}

func cssString(value string) string {
	value = strings.ReplaceAll(value, "</", "<\\/")
	return strconv.Quote(value)
}
