package server

import (
	"bytes"
	"html"
	"io"
	"net/http"
	"path"
	"strings"
	"time"

	"m31labs.dev/gosx"
	runtimehost "m31labs.dev/gosx/client/runtime/host"
	"m31labs.dev/gosx/internal/httpcache"
)

// navigationScriptWithNonce renders the framework-owned page-navigation
// runtime. It is intentionally unexported: App.EnableNavigation is the sole
// owner of this script, which prevents applications from accidentally
// creating a second runtime with a stale or missing request nonce.
func navigationScriptWithNonce(nonce string) gosx.Node {
	// Bootstrap scripts are also deferred. Document order keeps navigation
	// available before bootstrap without making first paint wait for this asset.
	// Omit integrity: cached HTML may request an older hash during a deploy,
	// and the server deliberately supplies current bytes with revalidation.
	return gosx.RawHTML(`<script data-gosx-navigation="true"` + nonceAttr(nonce) + ` defer crossorigin="anonymous" referrerpolicy="no-referrer" src="` + runtimehost.NavigationRuntimePath + `"></script>`)
}

func nonceAttr(nonce string) string {
	if nonce == "" {
		return ""
	}
	return ` nonce="` + html.EscapeString(nonce) + `"`
}

// serveNavigationRuntime serves generated bytes without request-time compression.
func (a *App) serveNavigationRuntime(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	if r.URL.Path == runtimehost.NavigationRuntimePath {
		httpcache.MarkImmutableAsset(w, r)
	} else {
		// Cached HTML can outlive the binary that emitted its navigation hash.
		// Revalidate fallback bytes on every reuse; they do not match that URL.
		w.Header().Set("Cache-Control", "no-cache")
	}
	w.Header().Set("ETag", `W/"`+strings.TrimSuffix(path.Base(runtimehost.NavigationRuntimePath), ".js")+`"`)
	MarkObservedRequest(r, "runtime", runtimehost.NavigationRuntimePath)
	var data io.ReadSeeker = strings.NewReader(runtimehost.NavigationRuntime)
	if !a.compressionOff {
		addAcceptEncodingVary(w.Header())
		if canServeCompressedFile(r) {
			if requestAcceptsBrotli(r) {
				data = bytes.NewReader(runtimehost.NavigationRuntimeBrotli)
				w.Header().Set("Content-Encoding", "br")
			} else if requestAcceptsGzip(r) {
				data = bytes.NewReader(runtimehost.NavigationRuntimeGzip)
				w.Header().Set("Content-Encoding", "gzip")
			}
		}
	}
	http.ServeContent(w, r, "navigation.js", time.Time{}, data)
}

// Link renders an anchor tag opted into the GoSX page-navigation runtime.
func Link(href string, args ...any) gosx.Node {
	attrs := gosx.Attrs(
		gosx.Attr("href", href),
		gosx.BoolAttr(NavigationLinkAttr),
		gosx.Attr(NavigationLinkStateAttr, "idle"),
		gosx.Attr(NavigationLinkCurrentPolicyAttr, "auto"),
		gosx.Attr(NavigationLinkPrefetchStateAttr, "idle"),
	)
	attrs = append(attrs, gosx.ProgressiveEnhancementAttrs(gosx.ProgressiveEnhancementOptions{
		Kind:     "navigation",
		Layer:    "bootstrap",
		Fallback: "native-link",
	})...)
	prefixed := append([]any{
		attrs,
	}, args...)
	return gosx.El("a", prefixed...)
}

// Form renders a form tag opted into the GoSX navigation/runtime submission
// layer while preserving native HTML fallback behavior.
func Form(args ...any) gosx.Node {
	prefixed := append([]any{
		gosx.ManagedFormAttrs(gosx.ManagedFormOptions{
			State:    "idle",
			Layer:    "bootstrap",
			Fallback: "native-form",
		}),
	}, args...)
	return gosx.El("form", prefixed...)
}

// HeadOutlet wraps head content in stable markers so the navigation runtime can
// replace managed head nodes during client-side page swaps.
func HeadOutlet(head gosx.Node) gosx.Node {
	return gosx.Fragment(
		gosx.RawHTML(`<meta name="gosx-head-start" content="">`),
		head,
		gosx.RawHTML(`<meta name="gosx-head-end" content="">`),
	)
}
