// Code generated by gosx. DO NOT EDIT.
package modules

import (
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/demos/cms"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/demos/scene3d"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/auth"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/forms"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/getting-started"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/images"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/routing"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/docs/runtime"
	_ "github.com/odvcencio/gosx/examples/gosx-docs/app/labs/stream"
)
