package wire

import "strings"

type loaderClassification string

const (
	loaderLiteral  loaderClassification = "modelled literal form"
	loaderDenied   loaderClassification = "denied token (incomplete)"
	loaderNotFetch loaderClassification = "not a fetch"
)

type loaderInventoryEntry struct {
	ID, API, Spec                                  string
	RelatedSpecs                                   []string
	Classification                                 loaderClassification
	Fetches                                        bool // May load a resource/document or start an application transport, including gates.
	DeniedTokens, EnumerationTokens, GlobalAliases string
	LiteralCalls                                   string // Fetching JavaScript callees with a modelled literal argument form.
	Model                                          string // Implemented form, or why a capability is conservatively denied.
}

// Audited 2026-10-10 against the specifications' fetch/activation algorithms,
// not just DOM/HTML names. A literal model covers only the named static form;
// mutations and other receiver/argument forms retain their denied tokens.
// "not a fetch" distinguishes value construction/metadata from loading; some
// such capabilities are still denied because they can escape into a loader.
// This table is the sole source of the token and literal-call policies: adding
// a token requires a specification row. Tests require witnesses for every row
// and exercise every fetching row in every permitted executable context.
var loaderInventory = []loaderInventoryEntry{
	{ID: "classic-script", API: "HTML classic script",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-script", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute(src), moduleReference; dynamic DOM changes denied"},
	{ID: "external-module-graph", API: "HTML external module graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-module-script-tree", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute(src), moduleReference; dynamic DOM changes denied"},
	{ID: "inline-module-graph", API: "HTML inline module graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-an-inline-module-script-graph", Classification: loaderLiteral, Fetches: true,
		Model: "moduleReference imports; scanDocumentTree inline body"},
	{ID: "module-descendants", API: "Module descendant linking",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-the-descendants-of-and-link-a-module-script", Classification: loaderLiteral, Fetches: true,
		Model: "moduleReference literal import/export/dynamic import; import-map resolution is unmodelled"},
	{ID: "single-module", API: "Single module fetch",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-single-module-script", Classification: loaderLiteral, Fetches: true,
		Model: "moduleReference literal import/export/dynamic import; import-map resolution is unmodelled"},
	{ID: "imported-module", API: "Imported module / dynamic import",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-single-imported-module-script", Classification: loaderLiteral, Fetches: true,
		LiteralCalls: "import",
		Model:        "moduleReference literal import/export/dynamic import; import-map resolution is unmodelled"},
	{ID: "modulepreload", API: "HTML modulepreload graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-modulepreload-module-script-graph", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "href",
		Model:        "scanHTMLReferenceAttribute(link href modulepreload); DOM mutation denied"},
	{ID: "classic-worker", API: "Dedicated classic worker",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-worker-script", Classification: loaderLiteral, Fetches: true,
		LiteralCalls: "Worker",
		Model:        "moduleReference literal Worker/SharedWorker and nested new URL"},
	{ID: "module-worker", API: "Dedicated module worker graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-module-worker-script-tree", Classification: loaderLiteral, Fetches: true,
		Model: "moduleReference literal Worker/SharedWorker and nested new URL"},
	{ID: "shared-classic-worker", API: "Shared classic worker",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-worker-script", Classification: loaderLiteral, Fetches: true,
		LiteralCalls: "SharedWorker",
		Model:        "moduleReference literal Worker/SharedWorker and nested new URL"},
	{ID: "shared-module-worker", API: "Shared module worker graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-module-worker-script-tree", Classification: loaderLiteral, Fetches: true,
		Model: "moduleReference literal Worker/SharedWorker and nested new URL"},
	{ID: "worker-importscripts", API: "Worker importScripts",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-classic-worker-imported-script", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "importScripts",
		Model:        "No importScripts argument-list model"},
	{ID: "worklet", API: "Worklet.addModule (paint, audio and other worklets)",
		Spec: "https://html.spec.whatwg.org/multipage/worklets.html#dom-worklet-addmodule", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "addModule",
		Model:        "No worklet module graph model"},
	{ID: "worklet-graph", API: "Worklet script graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-worklet-script-graph", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "addModule",
		Model:        "Worklet.addModule dispatches this algorithm"},
	{ID: "worklet-worker-common-graph", API: "Common worklet/module-worker graph",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#fetch-a-worklet/module-worker-script-graph", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "addModule",
		Model:        "Literal module Worker model; Worklet branch denied"},
	{ID: "import-map", API: "Import map registration/resolution",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#register-an-import-map", Classification: loaderNotFetch, Fetches: false,
		Model: "Registration resolves names, does not fetch; importmap scripts stay unresolved because that resolution is not modelled"},
	{ID: "speculation", API: "Speculation rules prefetch/prerender",
		Spec: "https://html.spec.whatwg.org/multipage/webappapis.html#register-speculation-rules", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "textContent",
		Model:        "Speculationrules script data and rule selection are unresolved, rule targets/gates are not modelled; HTTP response headers are outside this body-only scanner"},
	{ID: "image", API: "HTML img.src / Image",
		Spec: "https://html.spec.whatwg.org/multipage/images.html#updating-the-image-data", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "Image src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "input-image", API: "HTML input type=image",
		Spec: "https://html.spec.whatwg.org/multipage/input.html#image-button-state-(type=image)", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "audio", API: "HTML audio.src / Audio",
		Spec: "https://html.spec.whatwg.org/multipage/media.html#concept-media-load-resource", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "Audio load play src srcObject",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "video", API: "HTML video.src",
		Spec: "https://html.spec.whatwg.org/multipage/media.html#concept-media-load-resource", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "media-source", API: "HTML source.src",
		Spec: "https://html.spec.whatwg.org/multipage/media.html#concept-media-load-resource", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "track", API: "HTML track.src",
		Spec: "https://html.spec.whatwg.org/multipage/media.html#sourcing-in-band-text-tracks", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "poster", API: "HTML video.poster",
		Spec: "https://html.spec.whatwg.org/multipage/media.html#attr-video-poster", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "poster",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "iframe", API: "HTML iframe.src",
		Spec: "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#process-the-iframe-attributes", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "src",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "stylesheet", API: "HTML stylesheet link",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#link-type-stylesheet", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "href",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "preload", API: "HTML preload link",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#link-type-preload", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "href",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "prefetch", API: "HTML prefetch link",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#link-type-prefetch", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "href",
		Model:        "scanHTMLReferenceAttribute literal URL; dynamic property/activation denied"},
	{ID: "srcdoc", API: "HTML iframe.srcdoc document",
		Spec: "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#process-the-iframe-attributes", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "srcdoc",
		Model:        "scanSrcdocReferences; sandbox gates inherited"},
	{ID: "responsive-image", API: "HTML srcset / picture / imageSrcset selection",
		Spec: "https://html.spec.whatwg.org/multipage/images.html#select-an-image-source", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "srcset imageSrcset",
		Model:        "Responsive candidate selection is unresolved"},
	{ID: "embed", API: "HTML embed.src",
		Spec: "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "src",
		Model:        "Embedded response behavior is unresolved; URL retained"},
	{ID: "object", API: "HTML object.data",
		Spec: "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "data",
		Model:        "Object response behavior is unresolved; URL retained"},
	{ID: "icon", API: "HTML icon link",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#rel-icon", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "href",
		Model:        "This link/activation form has no reference model"},
	{ID: "hyperlink", API: "HTML hyperlink navigation/download",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "href click",
		Model:        "This link/activation form has no reference model"},
	{ID: "hyperlink-ping", API: "HTML hyperlink auditing",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#hyperlink-auditing", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "ping",
		Model:        "This link/activation form has no reference model"},
	{ID: "web-app-manifest", API: "Web App Manifest / installation images",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#link-type-manifest", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://www.w3.org/TR/appmanifest/#manifest-life-cycle"},
		DeniedTokens: "manifest href",
		Model:        "Manifest retrieval and optional installation/icon gates unresolved"},
	{ID: "web-app-manifest-images", API: "Web App Manifest installation/shortcut icons",
		Spec: "https://www.w3.org/TR/appmanifest/#dfn-fetch-a-manifest-image-resource", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "href manifest",
		Model:        "Image retrieval during installation/application presentation is unmodelled; the manifest link itself is unresolved"},
	{ID: "form-navigation", API: "HTML form action/formaction and submission",
		Spec: "https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-algorithm", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "action formaction formAction submit requestSubmit",
		Model:        "No submission/navigation model"},
	{ID: "meta-refresh", API: "HTML meta refresh",
		Spec: "https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-refresh", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "content httpEquiv",
		Model:        "Refresh targets are unresolved"},
	{ID: "navigation", API: "Location / window.open / Navigation API",
		Spec: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-location-interface", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-open", "https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigation-api"},
		DeniedTokens: "location assign replace open navigation navigate reload",
		Model:        "No navigation/redirect model"},
	{ID: "history-traversal", API: "History.go/back/forward",
		Spec: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-history-interface", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "history go back forward",
		Model:        "Traversal can retrieve another document; no history state model"},
	{ID: "navigation-traversal", API: "Navigation.back/forward/traverseTo",
		Spec: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigation-api", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "navigation back forward traverseTo",
		Model:        "Entry traversal can retrieve documents; no navigation state model"},
	{ID: "location-components", API: "Location URL component setters",
		Spec: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-location-interface", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "protocol host hostname port pathname search",
		Model:        "Location component mutation may navigate; unlike pure URL value mutation, its receiver/gates are unknown"},
	{ID: "svg-paint-url", API: "CSS/SVG fill/stroke/marker URL setters",
		Spec: "https://svgwg.org/svg2-draft/painting.html#SpecifyingPaint", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://svgwg.org/svg2-draft/painting.html#Markers"},
		DeniedTokens: "fill stroke marker markerStart markerMid markerEnd",
		Model:        "Paint and marker URL values can reference external resources; CSSOM receiver state unmodelled"},
	{ID: "svg-animated-url", API: "SVG animated URL baseVal setter",
		Spec: "https://svgwg.org/svg2-draft/types.html#InterfaceSVGAnimatedString", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://svgwg.org/svg2-draft/embedded.html#ImageElement"},
		DeniedTokens: "baseVal",
		Model:        "Writes the corresponding URL attribute on resource-bearing SVG elements; no animated-string receiver model"},
	{ID: "base-url", API: "HTML base.href",
		Spec: "https://html.spec.whatwg.org/multipage/semantics.html#the-base-element", Classification: loaderNotFetch, Fetches: false,
		DeniedTokens: "href",
		Model:        "Changing the base alone does not fetch, but changes URL resolution; base declarations remain unresolved"},
	{ID: "link-connections", API: "HTML dns-prefetch/preconnect",
		Spec: "https://html.spec.whatwg.org/multipage/links.html#link-type-preconnect", Classification: loaderNotFetch, Fetches: false,
		DeniedTokens: "href",
		Model:        "DNS/preconnect establishes connection state, not a resource fetch; unsupported link semantics remain unresolved"},
	{ID: "document-write", API: "HTML document.write/writeln/open",
		Spec: "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#document.write()", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "write writeln open",
		Model:        "Markup replacement can activate arbitrary dependencies"},
	{ID: "dom-create", API: "DOM creation/cloning/import",
		Spec: "https://dom.spec.whatwg.org/#interface-document", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://dom.spec.whatwg.org/#interface-node", "https://dom.spec.whatwg.org/#interface-range", "https://dom.spec.whatwg.org/#interface-domimplementation", "https://dom.spec.whatwg.org/#dom-element-attachshadow"},
		DeniedTokens: "createElement createElementNS cloneNode importNode adoptNode attachShadow cloneContents extractContents createDocument createHTMLDocument createProcessingInstruction",
		Model:        "Creation/cloning may carry resource attributes or escape to activation; no DOM state model"},
	{ID: "dom-insert", API: "DOM insertion/replacement activation",
		Spec: "https://dom.spec.whatwg.org/#interface-node", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://dom.spec.whatwg.org/#interface-parentnode", "https://dom.spec.whatwg.org/#interface-childnode", "https://dom.spec.whatwg.org/#interface-range", "https://dom.spec.whatwg.org/#dom-element-insertadjacentelement"},
		DeniedTokens: "appendChild append prepend insertBefore replaceChild replaceChildren replaceWith after before moveBefore insertAdjacentElement insertNode surroundContents",
		Model:        "May connect resource-bearing nodes; no mutation model"},
	{ID: "markup-parser", API: "HTML parsing/markup replacement",
		Spec: "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#html-parsing-methods", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-parsing-and-serialization", "https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-range-createcontextualfragment"},
		DeniedTokens: "insertAdjacentHTML innerHTML outerHTML DOMParser parseFromString createContextualFragment setHTML setHTMLUnsafe parseHTML parseHTMLUnsafe",
		Model:        "May create/activate resource-bearing documents/nodes; no parser-output model"},
	{ID: "attribute-mutation", API: "DOM attribute and character-data mutation",
		Spec: "https://dom.spec.whatwg.org/#interface-element", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://dom.spec.whatwg.org/#interface-attr", "https://dom.spec.whatwg.org/#interface-namednodemap", "https://dom.spec.whatwg.org/#interface-characterdata", "https://dom.spec.whatwg.org/#interface-text"},
		DeniedTokens: "setAttribute setAttributeNS setAttributeNode setAttributeNodeNS attributes setNamedItem setNamedItemNS getAttributeNode getAttributeNodeNS nodeValue textContent appendData insertData deleteData replaceData splitText replaceWholeText",
		Model:        "May mutate fetch URL fields, active style or other loading data"},
	{ID: "legacy-resource-fields", API: "HTML legacy resource fields",
		Spec: "https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "background archive codeBase classId code object lowsrc dynsrc dataSrc",
		Model:        "Legacy implementations/resource activation unresolved"},
	{ID: "metadata-url-fields", API: "HTML URL metadata and map references",
		Spec: "https://html.spec.whatwg.org/multipage/indices.html#attributes-3", Classification: loaderNotFetch, Fetches: false,
		DeniedTokens: "cite itemId itemType useMap longDesc profile",
		Model:        "These fields identify metadata/in-document maps, not a specified automatic fetch; retained conservative URL-field denial"},
	{ID: "option-video", API: "Option constructor / nonstandard Video token",
		Spec: "https://html.spec.whatwg.org/multipage/form-elements.html#dom-option", Classification: loaderNotFetch, Fetches: false,
		DeniedTokens: "Option Video",
		Model:        "Option creates an option node without fetching; Video is not an HTML global constructor; conservative legacy tokens retained"},
	{ID: "fetch", API: "Fetch API literal fetch",
		Spec: "https://fetch.spec.whatwg.org/#fetch-method", Classification: loaderLiteral, Fetches: true,
		LiteralCalls: "fetch",
		Model:        "moduleReference literal fetch; aliases/nonliteral URLs unresolved"},
	{ID: "fetch-later", API: "Fetch API deferred fetchLater",
		Spec: "https://fetch.spec.whatwg.org/#dom-window-fetchlater", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "fetchLater",
		Model:        "Deferred request activation/time gates unmodelled"},
	{ID: "request", API: "Fetch Request constructor",
		Spec: "https://fetch.spec.whatwg.org/#dom-request", Classification: loaderNotFetch, Fetches: false,
		DeniedTokens: "Request",
		Model:        "Constructs a Request without fetching; URL may escape to an unmodelled consumer"},
	{ID: "xhr", API: "XMLHttpRequest open/send",
		Spec: "https://xhr.spec.whatwg.org/#the-send()-method", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "XMLHttpRequest open send",
		Model:        "No XHR receiver/request state model"},
	{ID: "beacon", API: "Navigator.sendBeacon",
		Spec: "https://w3c.github.io/beacon/#sendbeacon-method", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "sendBeacon",
		Model:        "Beacon queue and payload gates unmodelled"},
	{ID: "eventsource", API: "EventSource connection/reconnect",
		Spec: "https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "EventSource",
		Model:        "Streaming/reconnect requests unmodelled"},
	{ID: "websocket", API: "WebSocket handshake",
		Spec: "https://websockets.spec.whatwg.org/#dom-websocket-websocket", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "WebSocket send",
		Model:        "Handshake and subsequent traffic unmodelled"},
	{ID: "service-worker", API: "ServiceWorkerContainer.register",
		Spec: "https://w3c.github.io/ServiceWorker/#navigator-service-worker-register", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "serviceWorker register",
		Model:        "Worker registration/type/update gates unmodelled"},
	{ID: "service-worker-update", API: "ServiceWorkerRegistration.update",
		Spec: "https://w3c.github.io/ServiceWorker/#service-worker-registration-update", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "update",
		Model:        "May refresh registered script graphs; receiver/gates unmodelled"},
	{ID: "cache-add", API: "Cache.add",
		Spec: "https://w3c.github.io/ServiceWorker/#cache-add", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "add",
		Model:        "Fetches RequestInfo before caching; no Cache receiver model"},
	{ID: "cache-addall", API: "Cache.addAll",
		Spec: "https://w3c.github.io/ServiceWorker/#cache-addAll", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "addAll",
		Model:        "Fetches each RequestInfo before caching"},
	{ID: "webtransport", API: "WebTransport connection",
		Spec: "https://w3c.github.io/webtransport/#webtransport-constructor", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "WebTransport",
		Model:        "Connection establishment/streams unmodelled (not a subresource HTTP fetch)"},
	{ID: "background-fetch", API: "BackgroundFetchManager.fetch",
		Spec: "https://wicg.github.io/background-fetch/#background-fetch-manager-fetch", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "backgroundFetch",
		Model:        "Job ID is not the URL; non-global fetch receivers, request-list/scheduling/UI gates unresolved"},
	{ID: "css-import", API: "CSS @import",
		Spec: "https://drafts.csswg.org/css-cascade-5/#at-import", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "insertRule addRule",
		Model:        "cssReference @import literal; CSSOM insertion denied"},
	{ID: "css-url", API: "CSS url()/image-set() resource values",
		Spec: "https://drafts.csswg.org/css-values-4/#urls", Classification: loaderLiteral, Fetches: true,
		DeniedTokens: "style cssText setProperty",
		Model:        "cssReference literal url/image-set; CSSOM mutation denied"},
	{ID: "css-property-setters", API: "CSSOM resource-valued property setters",
		Spec: "https://drafts.csswg.org/cssom/#cssstyledeclaration", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://drafts.csswg.org/css-values-4/#urls"},
		DeniedTokens: "background backgroundImage borderImage borderImageSource listStyle listStyleImage cursor content mask maskImage maskBorderSource shapeOutside filter clipPath offsetPath",
		Model:        "Camel-case setters can introduce URLs on an aliased declaration without a style token"},
	{ID: "css-replace", API: "CSSStyleSheet.replace / replaceSync",
		Spec: "https://drafts.csswg.org/cssom/#dom-cssstylesheet-replace", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://drafts.csswg.org/cssom/#dom-cssstylesheet-replacesync", "https://drafts.csswg.org/css-values-4/#urls"},
		DeniedTokens: "replace replaceSync",
		Model:        "Constructed sheets remove @import rules, but url() resources can load when adopted/used; no sheet state model"},
	{ID: "css-typed-om", API: "CSS Typed OM attributeStyleMap/styleMap mutation",
		Spec: "https://drafts.css-houdini.org/css-typed-om-1/#stylepropertymap", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "attributeStyleMap styleMap",
		Model:        "Typed values can activate resource-valued CSS; receiver/value model absent"},
	{ID: "fontface", API: "FontFace URL source / load",
		Spec: "https://drafts.csswg.org/css-font-loading/#font-face-load", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "FontFace load",
		Model:        "URL sources can fetch when loaded/used; binary sources alone do not fetch"},
	{ID: "fontset", API: "Document.fonts.load / FontFaceSet.load",
		Spec: "https://drafts.csswg.org/css-font-loading/#font-face-set-load", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "load",
		Model:        "Selects and loads matching font faces"},
	{ID: "notification", API: "Notification constructor images/icons/badges/action icons",
		Spec: "https://notifications.spec.whatwg.org/#fetch-steps", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "Notification",
		Model:        "Notification fetch steps may retrieve each configured resource; platform gates unmodelled"},
	{ID: "push-notification", API: "Persistent / Push notification resource images",
		Spec: "https://notifications.spec.whatwg.org/#dom-serviceworkerregistration-shownotification", Classification: loaderDenied, Fetches: true,
		RelatedSpecs: []string{"https://notifications.spec.whatwg.org/#fetch-steps", "https://www.w3.org/TR/push-api/#push-message"},
		DeniedTokens: "showNotification",
		Model:        "Push handling calls showNotification; same gated image/icon/badge/action fetch steps; declarative push payloads are outside page source"},
	{ID: "push-subscribe", API: "PushManager.subscribe",
		Spec: "https://www.w3.org/TR/push-api/#dom-pushmanager-subscribe", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "pushManager subscribe",
		Model:        "May contact push service to create subscription; not an icon fetch by itself"},
	{ID: "payment-method", API: "Payment Request URL payment-method manifests",
		Spec: "https://w3c.github.io/payment-method-manifest/#fetch-pmm", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "PaymentRequest show canMakePayment",
		Model:        "URL identifiers can cause method-manifest discovery/fetch during payment flow; no payment state model"},
	{ID: "payment-app", API: "Payment default application manifest/icons",
		Spec: "https://w3c.github.io/payment-method-manifest/#fetch-the-web-app-manifest-for-a-default-payment-app", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "PaymentRequest show",
		Model:        "Default payment app manifest fetch and installation gates unmodelled"},
	{ID: "url", API: "URL constructor / import.meta.url hint",
		Spec: "https://url.spec.whatwg.org/#dom-url-url", Classification: loaderNotFetch, Fetches: false,
		Model: "Constructor itself does not fetch; moduleReference records its literal URL hint"},
	{ID: "timers", API: "HTML inline-function timers",
		Spec: "https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers", Classification: loaderNotFetch, Fetches: false,
		Model: "Timers do not fetch by themselves; literal nested loaders scanned, string/opaque callbacks unresolved"},
	{ID: "code-construction", API: "ECMAScript eval/Function/constructor escape",
		Spec: "https://tc39.es/ecma262/#sec-function-constructor", Classification: loaderNotFetch, Fetches: false,
		RelatedSpecs: []string{"https://tc39.es/ecma262/#sec-eval-x"},
		DeniedTokens: "eval Function constructor",
		Model:        "Constructed code does not inherently fetch but can conceal arbitrary loaders; always denied"},
	{ID: "reflection", API: "ECMAScript Reflect and object mutation/reflection",
		Spec: "https://tc39.es/ecma262/#sec-reflect-object", Classification: loaderNotFetch, Fetches: false,
		RelatedSpecs: []string{"https://tc39.es/ecma262/#sec-properties-of-the-object-constructor", "https://tc39.es/ecma262/#sec-object.prototype.__proto__"},
		DeniedTokens: "Reflect getOwnPropertyDescriptor getOwnPropertyDescriptors __proto__ getPrototypeOf setPrototypeOf defineProperty defineProperties assign",
		Model:        "No fetch itself; can expose/replace loader capabilities, always denied"},
	{ID: "enumeration", API: "ECMAScript object enumeration/fromEntries",
		Spec: "https://tc39.es/ecma262/#sec-properties-of-the-object-constructor", Classification: loaderNotFetch, Fetches: false,
		EnumerationTokens: "values entries keys getOwnPropertyNames getOwnPropertySymbols getOwnPropertyDescriptor getOwnPropertyDescriptors getPrototypeOf fromEntries assign",
		Model:             "No fetch itself; exposes loader capabilities; keys/property uses denied, ordinary local names allowed"},
	{ID: "global-aliases", API: "HTML/ECMAScript global-object aliases",
		Spec: "https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-window-object", Classification: loaderNotFetch, Fetches: false,
		RelatedSpecs:  []string{"https://tc39.es/ecma262/#sec-globalthis", "https://html.spec.whatwg.org/multipage/nav-history-apis.html#dom-document-defaultview"},
		GlobalAliases: "globalThis window self top parent frames opener defaultView",
		Model:         "No fetch itself; aliasing outside static alias.name is unresolved"},
	{ID: "custom-elements", API: "CustomElements.define / upgrade",
		Spec: "https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api", Classification: loaderDenied, Fetches: true,
		DeniedTokens: "customElements define upgrade",
		Model:        "Callbacks may activate resource-bearing nodes; no upgrade/callback model"},
}

func inventoryTokens(field func(loaderInventoryEntry) string) map[string]bool {
	tokens := make(map[string]bool)
	for _, row := range loaderInventory {
		for _, token := range strings.Fields(field(row)) {
			tokens[token] = true
		}
	}
	return tokens
}

var deniedLoaderTokens = inventoryTokens(func(row loaderInventoryEntry) string { return row.DeniedTokens })
var enumerationLoaderTokens = inventoryTokens(func(row loaderInventoryEntry) string { return row.EnumerationTokens })
var globalObjectAliases = inventoryTokens(func(row loaderInventoryEntry) string { return row.GlobalAliases })

var literalLoaderCalls = inventoryTokens(func(row loaderInventoryEntry) string { return row.LiteralCalls })
