package docs

import (
	_ "embed"
	"encoding/json"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	docsapp "m31labs.dev/gosx/examples/gosx-docs/app"
	"m31labs.dev/gosx/hydrate"
	"m31labs.dev/gosx/route"
	"m31labs.dev/gosx/server"
)

type TabletopReceipt struct {
	SourceFiles     []TabletopSourceFile `json:"sourceFiles"`
	JavaScriptLines int                  `json:"javascriptLines"`
}

type TabletopSourceFile struct {
	Path  string `json:"path"`
	Lines int    `json:"lines"`
}

type TabletopControlsProps struct {
	ShareURL string
}

// The source receipt is generated by scripts/generate-tabletop-receipts.go
// and checked against the source tree in rooms_test.go.
//
//go:embed receipts.json
var tabletopReceiptData []byte

var currentTabletopReceipt TabletopReceipt

func init() {
	if err := json.Unmarshal(tabletopReceiptData, &currentTabletopReceipt); err != nil {
		panic(err)
	}
}

func init() {
	docsapp.RegisterDocsPage("Shared Tabletop", "Place and arrange Poly Haven models in one realtime GoSX room, backed by a CRDT document and Scene3D.", route.FileModuleOptions{
		Load: func(ctx *route.RouteContext, page route.FilePage) (any, error) {
			room, _, err := Rooms.GetForPage(ctx.Query("room"), time.Now())
			if err != nil {
				return nil, route.NotFound("This tabletop room is unavailable.")
			}
			runtime := ctx.Runtime()
			runtime.SetTextureVariants(tabletopTextureVariants)
			runtime.BindHubWithRoundTrip("tabletop", "/demos/tabletop/ws/?room="+url.QueryEscape(room.ID), []hydrate.HubBinding{
				{Event: "scene:update", SceneMountID: "tabletop-scene", SceneCommands: true},
				{Event: "scene:pick", Direction: "out", SceneMountID: "tabletop-scene", SceneInput: "pick"},
				{Event: "presence:pointer", Signal: "$tabletop.cursor", Direction: "out", ThrottleMS: 67},
				{Event: "palette", Signal: "$tabletop.palette", Direction: "out"},
				{Event: "lighting", Signal: "$tabletop.lighting", Direction: "out"},
				{Event: "object:rotate", Signal: "$tabletop.rotate", Direction: "out"},
				{Event: "object:remove", Signal: "$tabletop.remove", Direction: "out"},
				{Event: "room:selected", Signal: "$tabletop.selected"},
			}, hydrate.HubRoundTripConfig{
				Signal: "$tabletop.rtt", PingEvent: "room:ping", PongEvent: "room:pong", IntervalMS: 1500,
			})
			metrics := room.Metrics()
			poster := server.ScenePosterConfig{
				URL: "/tabletop/tabletop-poster.webp", Alt: "Six objects arranged on a textured tabletop before this room's edits",
				Width: 1100, Height: 760,
			}
			ctx.AddHead(server.ScenePosterPreload(poster))
			return map[string]any{
				"scene":         room.Props(),
				"posterURL":     server.AssetURL(poster.URL),
				"roomID":        room.ID,
				"shareURL":      tabletopShareURL(ctx, room.ID),
				"visitors":      metrics.Visitors,
				"objects":       metrics.Objects,
				"documentBytes": metrics.DocumentBytes,
				"lighting":      metrics.Lighting,
				"receipt":       currentTabletopReceipt,
			}, nil
		},
	})
}

func tabletopShareURL(ctx *route.RouteContext, roomID string) string {
	base := strings.TrimRight(strings.TrimSpace(os.Getenv("PUBLIC_URL")), "/")
	if base == "" && ctx != nil && ctx.Request != nil {
		request := ctx.Request
		scheme := "http"
		if request.TLS != nil {
			scheme = "https"
		} else if forwarded := strings.TrimSpace(strings.Split(request.Header.Get("X-Forwarded-Proto"), ",")[0]); forwarded == "https" {
			scheme = "https"
		}
		base = scheme + "://" + request.Host
	}
	return base + "/demos/tabletop?room=" + url.QueryEscape(roomID)
}

// PrivateRoomRedirect assigns a random room to a direct visit to the demo
// route. Shared links already include a room id and pass through unchanged.
func PrivateRoomRedirect(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.URL.Query().Get("room") != "" {
			next.ServeHTTP(w, req)
			return
		}
		roomID, err := Rooms.NewPrivateRoomID()
		if err != nil {
			http.Error(w, "Tabletop rooms are busy. Try again shortly.", http.StatusServiceUnavailable)
			return
		}
		target := *req.URL
		query := target.Query()
		query.Set("room", roomID)
		target.RawQuery = query.Encode()
		http.Redirect(w, req, target.String(), http.StatusFound)
	})
}

// RoomRouteMiddleware keeps the dynamic room page out of ISR's path-only
// artifact cache and normalizes its directory alias to the queryable route.
func RoomRouteMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		if req.URL == nil || (req.Method != http.MethodGet && req.Method != http.MethodHead) {
			next.ServeHTTP(w, req)
			return
		}
		if req.URL.Path == "/demos/tabletop/" {
			target := *req.URL
			target.Path = "/demos/tabletop"
			http.Redirect(w, req, target.String(), http.StatusPermanentRedirect)
			return
		}
		if req.URL.Path == "/demos/tabletop" {
			// GoSX's ISR stores one artifact per path and cannot key room pages by
			// query parameters. This internal signal is added after public headers
			// are sanitized and before ISR dispatch.
			req.Header.Set("X-GoSX-ISR-Revalidate", "tabletop-room")
		}
		next.ServeHTTP(w, req)
	})
}
