package docs

import (
	"context"
	"crypto/rand"
	_ "embed"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net/http"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/gorilla/websocket"
	"m31labs.dev/gosx/assetpipe"
	"m31labs.dev/gosx/crdt"
	"m31labs.dev/gosx/hub"
	"m31labs.dev/gosx/hub/scene3d"
	"m31labs.dev/gosx/scene"
)

const (
	maxTabletopObjects  = 64
	maxTabletopVisitors = 8
	maxTabletopRooms    = 200
	tabletopRoomIdle    = 30 * time.Minute
	tabletopSurfaceEdge = 2.15
	tabletopSurfaceTop  = 0.0645
	tabletopContactPad  = 0.002
	tabletopObjectBase  = tabletopSurfaceTop + tabletopContactPad
)

var (
	ErrInvalidRoomID = errors.New("tabletop: room id must be 16 lowercase hexadecimal characters")
	ErrRoomLimit     = errors.New("tabletop: room limit reached")
	ErrInvalidKind   = errors.New("tabletop: unknown object kind")
	ErrOutOfBounds   = errors.New("tabletop: placement is outside the diorama surface")
	ErrObjectLimit   = errors.New("tabletop: room object limit reached")
	ErrRateLimit     = errors.New("tabletop: client rate limit reached")
)

var tabletopKinds = map[string]scene.Model{
	// These compact typed mesh groups preserve the still life's variety without
	// downloading three more model packages.
	"ceramic": {},
	"brass":   {},
	"plant":   {ID: "", Src: "/tabletop/models/potted_plant_04/potted_plant_04_1k.opt.glb"},
	"book":    {},
	"candle":  {},
	"orb":     {},
}

// The bake is generated by scripts/generate-tabletop-assets.go from the
// Poly Haven Studio Small 09 HDRI.
//
//go:embed ibl.json
var tabletopIBLData []byte

var tabletopIBL scene.EnvironmentIBL

// Texture variants are generated beside the public models by assetpipe. The
// browser chooses BC KTX2 files only when the active renderer reports support.
//
//go:embed texture-variants.json
var tabletopTextureVariantData []byte

var tabletopTextureVariants assetpipe.VariantManifest

func init() {
	if err := json.Unmarshal(tabletopIBLData, &tabletopIBL); err != nil {
		panic(err)
	}
	if err := json.Unmarshal(tabletopTextureVariantData, &tabletopTextureVariants); err != nil {
		panic(err)
	}
}

// Rooms holds the in-memory rooms served by the tabletop route.
var Rooms = NewRoomManager()

type tabletopObject struct {
	ID        string
	Kind      string
	X         float64
	Z         float64
	RotationY float64
}

type visitorPointer struct {
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	WorldX float64 `json:"worldX"`
	WorldZ float64 `json:"worldZ"`
	Color  string  `json:"color"`
}

type roomRateWindow struct {
	events []time.Time
}

// Room owns the server-authoritative scene and its synchronized CRDT document.
// Pointer and selection state is ephemeral; model placement and lighting are
// written to the document and reach peers through its watcher.
type Room struct {
	ID  string
	Hub *hub.Hub

	doc          *scene3d.Doc
	mu           sync.RWMutex
	props        scene.Props
	initialProps scene.Props
	objects      map[string]tabletopObject
	palette      map[string]string
	selected     map[string]string
	visitors     map[string]struct{}
	pointers     map[string]visitorPointer
	ptrSlots     map[string]int
	rates        map[string]map[string]*roomRateWindow
	lighting     string
	nextID       uint64
	lastUse      time.Time
	revision     atomic.Uint64
}

// RoomManager bounds in-memory private rooms and retires rooms that have no
// visitors and have been inactive for the configured interval.
type RoomManager struct {
	mu       sync.Mutex
	rooms    map[string]*Room
	maxRooms int
	idle     time.Duration
	newID    func() (string, error)
}

func NewRoomManager() *RoomManager {
	return &RoomManager{rooms: make(map[string]*Room), maxRooms: maxTabletopRooms, idle: tabletopRoomIdle, newID: randomRoomID}
}

// StartRoomJanitor deletes inactive rooms every minute until ctx is canceled.
func StartRoomJanitor(ctx context.Context) {
	if ctx == nil {
		ctx = context.Background()
	}
	go func() {
		ticker := time.NewTicker(time.Minute)
		defer ticker.Stop()
		for {
			select {
			case now := <-ticker.C:
				Rooms.Sweep(now)
			case <-ctx.Done():
				return
			}
		}
	}()
}

// ServeWebSocket resolves a room from the query string and serves its hub.
func ServeWebSocket(w http.ResponseWriter, req *http.Request) {
	if !validTabletopWebSocketRequest(req) {
		http.Error(w, "A valid same-origin WebSocket upgrade is required.", http.StatusBadRequest)
		return
	}
	room, err := Rooms.GetOrCreate(req.URL.Query().Get("room"), time.Now())
	if err != nil {
		http.Error(w, "This tabletop room is unavailable.", http.StatusNotFound)
		return
	}
	room.Hub.ServeHTTP(w, req)
}

func validTabletopWebSocketRequest(req *http.Request) bool {
	if req == nil || req.URL == nil || req.Method != http.MethodGet || !websocket.IsWebSocketUpgrade(req) {
		return false
	}
	if req.Header.Get("Sec-WebSocket-Version") != "13" {
		return false
	}
	key, err := base64.StdEncoding.DecodeString(req.Header.Get("Sec-WebSocket-Key"))
	if err != nil || len(key) != 16 {
		return false
	}
	origin := req.Header.Get("Origin")
	return origin != "" && (origin == "http://"+req.Host || origin == "https://"+req.Host)
}

// NewPrivateRoomID returns an unpredictable room URL without reserving a
// room. A page view alone must not consume one of the server's bounded slots.
func (m *RoomManager) NewPrivateRoomID() (string, error) {
	for attempt := 0; attempt < 8; attempt++ {
		id, err := m.newID()
		if err != nil {
			return "", err
		}
		if !validTabletopRoomID(id) {
			return "", ErrInvalidRoomID
		}
		m.mu.Lock()
		_, exists := m.rooms[id]
		m.mu.Unlock()
		if !exists {
			return id, nil
		}
	}
	return "", fmt.Errorf("tabletop: could not generate an unused room identifier")
}

// GetOrCreate returns the named room, refreshing its idle deadline, or creates
// it if the identifier is valid and the active-room cap has room.
func (m *RoomManager) GetOrCreate(id string, now time.Time) (*Room, error) {
	id = strings.TrimSpace(id)
	if !validTabletopRoomID(id) {
		return nil, ErrInvalidRoomID
	}
	m.mu.Lock()
	defer m.mu.Unlock()
	if room := m.rooms[id]; room != nil {
		room.touch(now)
		return room, nil
	}
	if len(m.rooms) >= m.maxRooms {
		return nil, ErrRoomLimit
	}
	room := newTabletopRoom(id, now)
	m.rooms[id] = room
	return room, nil
}

// GetForPage returns an active room or a temporary initial scene for a room
// link that has not connected yet. It never reserves a manager slot for a
// normal HTTP page request; the WebSocket handler creates the room after
// validating the upgrade request.
func (m *RoomManager) GetForPage(id string, now time.Time) (*Room, bool, error) {
	id = strings.TrimSpace(id)
	if !validTabletopRoomID(id) {
		return nil, false, ErrInvalidRoomID
	}
	m.mu.Lock()
	if room := m.rooms[id]; room != nil {
		room.touch(now)
		m.mu.Unlock()
		return room, true, nil
	}
	if len(m.rooms) >= m.maxRooms {
		m.mu.Unlock()
		return nil, false, ErrRoomLimit
	}
	m.mu.Unlock()
	return newTabletopRoom(id, now), false, nil
}

// Sweep removes rooms that exceeded the idle period and have no connected
// visitors. It returns the number of deleted rooms.
func (m *RoomManager) Sweep(now time.Time) int {
	m.mu.Lock()
	defer m.mu.Unlock()
	removed := 0
	for id, room := range m.rooms {
		if room.Hub.ClientCount() != 0 || now.Sub(room.lastUsed()) < m.idle {
			continue
		}
		delete(m.rooms, id)
		removed++
	}
	return removed
}

func (m *RoomManager) Count() int {
	m.mu.Lock()
	defer m.mu.Unlock()
	return len(m.rooms)
}

func randomRoomID() (string, error) {
	var raw [8]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(raw[:]), nil
}

func validTabletopRoomID(id string) bool {
	if len(id) != 16 {
		return false
	}
	for _, c := range id {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

func newTabletopRoom(id string, now time.Time) *Room {
	h := hub.New("tabletop-" + id)
	h.RequireOrigin = true
	h.MaxClients = maxTabletopVisitors
	h.MaxMessagesPerSecond = 30
	h.MaxMessageBurst = 60
	document := crdt.NewDoc()
	sceneDoc, err := scene3d.Bind(document, "tabletop")
	if err != nil {
		panic(err)
	}
	r := &Room{
		ID: id, Hub: h, doc: sceneDoc,
		objects:  make(map[string]tabletopObject),
		palette:  make(map[string]string),
		selected: make(map[string]string),
		visitors: make(map[string]struct{}),
		pointers: make(map[string]visitorPointer),
		rates:    make(map[string]map[string]*roomRateWindow),
		ptrSlots: make(map[string]int),
		lighting: "softbox", lastUse: now,
	}
	r.seedObjectsLocked()
	r.props = r.scenePropsLocked()
	r.initialProps = r.props
	seedCommands := scene.DiffPropsCommands(scene.Props{}, r.props)
	if _, err := r.doc.Apply(seedCommands, "seed tabletop"); err != nil {
		panic(err)
	}
	r.doc.Watch(func(commands []scene.Command) {
		if len(commands) == 0 {
			return
		}
		// Command bindings keep only the latest event while a renderer is
		// mounting, so publish the current diff from the room's original scene.
		go r.broadcastSceneSnapshot()
	})
	r.Hub.SetBinaryAuthorizer(func(_ *hub.Client, _ string) bool { return false })
	r.Hub.SyncDoc("scene", r.doc.Doc())
	r.installHandlers()
	return r
}

func (r *Room) installHandlers() {
	r.Hub.On("join", func(ctx *hub.Context) {
		now := time.Now()
		if !r.addVisitor(ctx.Client.ID, now) {
			return
		}
		r.sendSceneSnapshot(ctx.Client.ID)
		r.broadcastPresence()
		r.sendMetrics(ctx.Client.ID)
	})
	r.Hub.On("leave", func(ctx *hub.Context) {
		r.removeVisitor(ctx.Client.ID, time.Now())
		r.broadcastPresence()
		r.broadcastSceneSnapshot()
	})
	r.Hub.On("palette", func(ctx *hub.Context) {
		var kind string
		if json.Unmarshal(ctx.Data, &kind) != nil || !knownTabletopKind(kind) || !r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			return
		}
		r.mu.Lock()
		r.palette[ctx.Client.ID] = kind
		r.touchLocked(time.Now())
		r.mu.Unlock()
	})
	r.Hub.On("lighting", func(ctx *hub.Context) {
		var preset string
		if json.Unmarshal(ctx.Data, &preset) != nil || !knownLightingPreset(preset) || !r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			return
		}
		r.mu.Lock()
		previous := r.props.SceneIR()
		r.lighting = preset
		commands, err := r.applyPropsLocked(previous, "change tabletop light")
		r.mu.Unlock()
		if err == nil && len(commands) > 0 {
			r.sendMetrics("")
		}
	})
	r.Hub.On("scene:pick", func(ctx *hub.Context) {
		if !r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			return
		}
		var payload struct {
			Input struct {
				Type     string  `json:"type"`
				TargetID string  `json:"targetID"`
				WorldX   float64 `json:"worldX"`
				WorldZ   float64 `json:"worldZ"`
			} `json:"input"`
		}
		if json.Unmarshal(ctx.Data, &payload) != nil || payload.Input.Type != "select" {
			return
		}
		if payload.Input.TargetID == "tabletop-surface" {
			if r.placeAt(ctx.Client.ID, payload.Input.WorldX, payload.Input.WorldZ, time.Now()) == nil {
				r.sendMetrics("")
				r.sendSelection(ctx.Client.ID)
			}
			return
		}
		r.mu.Lock()
		if _, ok := r.objects[payload.Input.TargetID]; ok {
			r.selected[ctx.Client.ID] = payload.Input.TargetID
		}
		r.touchLocked(time.Now())
		r.mu.Unlock()
		r.sendMetrics("")
		r.sendSelection(ctx.Client.ID)
	})
	r.Hub.On("action", func(ctx *hub.Context) {
		var action string
		if json.Unmarshal(ctx.Data, &action) != nil || !r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			return
		}
		r.mutateSelection(ctx.Client.ID, action, time.Now())
	})
	r.Hub.On("object:rotate", func(ctx *hub.Context) {
		if r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			r.mutateSelection(ctx.Client.ID, "rotate", time.Now())
		}
	})
	r.Hub.On("object:remove", func(ctx *hub.Context) {
		if r.allow(ctx.Client.ID, "edit", time.Now(), 20) {
			r.mutateSelection(ctx.Client.ID, "remove", time.Now())
		}
	})
	r.Hub.On("presence:pointer", func(ctx *hub.Context) {
		if !r.allow(ctx.Client.ID, "pointer", time.Now(), 15) {
			return
		}
		var point visitorPointer
		if json.Unmarshal(ctx.Data, &point) != nil || !finite(point.X) || !finite(point.Y) || point.X < 0 || point.X > 1 || point.Y < 0 || point.Y > 1 {
			return
		}
		r.mu.Lock()
		if _, joined := r.visitors[ctx.Client.ID]; !joined {
			r.mu.Unlock()
			return
		}
		point.Color = visitorColor(ctx.Client.ID)
		point.WorldX, point.WorldZ = pointerWorldPosition(point.X, point.Y)
		r.pointers[ctx.Client.ID] = point
		commands := r.sceneSnapshotCommandsLocked(r.scenePropsWithPointersLocked())
		revision := r.revision.Add(1)
		r.touchLocked(time.Now())
		r.mu.Unlock()
		r.Hub.Broadcast("scene:update", scene.MountCommandBatch{Revision: revision, Commands: commands})
	})
	r.Hub.On("room:ping", func(ctx *hub.Context) {
		r.Hub.Send(ctx.Client.ID, "room:pong", json.RawMessage(ctx.Data))
	})
}

func (r *Room) seedObjectsLocked() {
	r.objects["prop-ceramic"] = tabletopObject{ID: "prop-ceramic", Kind: "ceramic", X: -0.78, Z: 0.16}
	r.objects["prop-brass"] = tabletopObject{ID: "prop-brass", Kind: "brass", X: 0.82, Z: 0.08, RotationY: 0.45}
	r.objects["prop-plant"] = tabletopObject{ID: "prop-plant", Kind: "plant", X: -1.12, Z: -0.82}
	r.objects["prop-book"] = tabletopObject{ID: "prop-book", Kind: "book", X: -0.95, Z: 1.05, RotationY: 0.2}
	r.objects["prop-candle"] = tabletopObject{ID: "prop-candle", Kind: "candle", X: 0.45, Z: 0.55}
	r.objects["prop-orb"] = tabletopObject{ID: "prop-orb", Kind: "orb", X: 1.5, Z: -1.0}
	r.nextID = uint64(len(r.objects))
}

func (r *Room) Props() scene.Props {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.scenePropsWithPointersLocked()
}

// RoomMetrics is a server-renderable snapshot of room presence, scene state,
// and the serialized CRDT document size.
type RoomMetrics struct {
	Visitors      int
	Objects       int
	DocumentBytes int
	Lighting      string
}

func (r *Room) Metrics() RoomMetrics {
	document, err := r.doc.Doc().Save()
	if err != nil {
		document = nil
	}
	r.mu.RLock()
	defer r.mu.RUnlock()
	return RoomMetrics{Visitors: len(r.visitors), Objects: len(r.objects), DocumentBytes: len(document), Lighting: r.lighting}
}

func (r *Room) scenePropsLocked() scene.Props {
	light := lightingPreset(r.lighting)
	nodes := []scene.Node{
		// PlaneGeometry is a camera-facing studio sweep behind the objects. Its
		// center sits on the camera's view ray so the cool edge and warm pool
		// cover the full render instead of cutting across the table.
		scene.Mesh{ID: "tabletop-studio-backdrop", Geometry: scene.PlaneGeometry{Width: 14, Height: 8}, Material: scene.FlatMaterial{Color: "#ffffff", Texture: "/tabletop/studio-sweep.png"}, Position: scene.Vec3(-3.9, -2.0, -4.0), Rotation: scene.Euler{X: 1.16, Y: 0.75}, Pickable: scene.Bool(false)},
		scene.DirectionalLight{ID: "tabletop-key", Color: light.KeyColor, Intensity: light.KeyIntensity, Direction: scene.Vec3(-0.42, -1, -0.55), CastShadow: true, ShadowBias: -0.001, ShadowSize: 1024, ShadowSoftness: 0.55},
		scene.HemisphereLight{ID: "tabletop-fill", SkyColor: light.SkyColor, GroundColor: "#403b37", Intensity: light.FillIntensity},
		scene.PointLight{ID: "tabletop-rim", Color: light.RimColor, Intensity: 0.65, Position: scene.Vec3(-2.7, 2.2, -1.8), Range: 10, Decay: 2},
		scene.Mesh{ID: "tabletop-base", Geometry: scene.CylinderGeometry{RadiusTop: 2.42, RadiusBottom: 2.52, Height: 0.34, Segments: 128}, Material: scene.StandardMaterial{Color: "#34241e", Roughness: 0.32, Metalness: 0.08, Clearcoat: 0.32}, Position: scene.Vec3(0, -0.2, 0), CastShadow: true, ReceiveShadow: true},
		scene.Mesh{ID: "tabletop-inset", Geometry: scene.CylinderGeometry{RadiusTop: 2.25, RadiusBottom: 2.3, Height: 0.07, Segments: 128}, Material: scene.StandardMaterial{Color: "#514037", Roughness: 0.28, Metalness: 0.08, Clearcoat: 0.4}, Position: scene.Vec3(0, 0.005, 0), ReceiveShadow: true},
		scene.Mesh{ID: "tabletop-brass-line", Geometry: scene.TorusGeometry{Radius: 2.30, Tube: 0.018, RadialSegments: 128, TubularSegments: 8}, Material: scene.StandardMaterial{Color: "#bd955d", Roughness: 0.26, Metalness: 0.76}, Position: scene.Vec3(0, 0.03, 0)},
		// The Poly Haven wood map set (albedo, OpenGL normal, roughness) gives
		// the broad tabletop enough grain to read at phone scale. Its warm
		// neutral tint avoids shifting the authored wood into orange.
		scene.Mesh{ID: "tabletop-surface", Geometry: scene.CylinderGeometry{RadiusTop: 2.20, RadiusBottom: 2.20, Height: 0.025, Segments: 128}, Material: scene.StandardMaterial{
			Color: "#d4c2ad", Texture: "/tabletop/surfaces/wood_table_001/wood_table_001_diff.png",
			NormalMap: "/tabletop/surfaces/wood_table_001/wood_table_001_nor_gl.png", RoughnessMap: "/tabletop/surfaces/wood_table_001/wood_table_001_rough.png",
			Roughness: 0.7, Metalness: 0.02,
		}, Position: scene.Vec3(0, 0.052, 0), Pickable: scene.Bool(true), ReceiveShadow: true},
	}
	ids := make([]string, 0, len(r.objects))
	for id := range r.objects {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		object := r.objects[id]
		nodes = append(nodes, tabletopContactShadow(object))
		if object.Kind == "ceramic" {
			// Muted ceramic and a narrow lip preserve detail without clipped white
			// highlights. The body is the pick target; all parts cast soft shadows.
			nodes = append(nodes, scene.Group{
				ID: object.ID + "-root", Position: scene.Vec3(object.X, tabletopObjectBase, object.Z), Rotation: scene.Euler{Y: object.RotationY},
				Children: []scene.Node{
					scene.Mesh{ID: object.ID, Geometry: scene.SphereGeometry{Radius: 0.27, Segments: 32}, Material: scene.StandardMaterial{Color: "#d4c2ad", Roughness: 0.34, Clearcoat: 0.34}, Position: scene.Vec3(0, 0.31, 0), Scale: scene.Vec3(1, 1.15, 1), CastShadow: true, ReceiveShadow: true, Pickable: scene.Bool(true)},
					scene.Mesh{ID: object.ID + "-neck", Geometry: scene.CylinderGeometry{RadiusTop: 0.13, RadiusBottom: 0.16, Height: 0.34, Segments: 40}, Material: scene.StandardMaterial{Color: "#d4c2ad", Roughness: 0.34, Clearcoat: 0.34}, Position: scene.Vec3(0, 0.57, 0), CastShadow: true, ReceiveShadow: true},
					scene.Mesh{ID: object.ID + "-lip", Geometry: scene.TorusGeometry{Radius: 0.14, Tube: 0.018, RadialSegments: 12, TubularSegments: 40}, Material: scene.StandardMaterial{Color: "#d4c2ad", Roughness: 0.34, Clearcoat: 0.34}, Position: scene.Vec3(0, 0.75, 0), CastShadow: true, ReceiveShadow: true},
				},
			})
			continue
		}
		if object.Kind == "brass" {
			// Turned brass forms a taller, narrower silhouette than the books.
			gold := scene.StandardMaterial{Color: "#bd955d", Roughness: 0.3, Metalness: 0.72}
			nodes = append(nodes, scene.Group{
				ID: object.ID + "-root", Position: scene.Vec3(object.X, tabletopObjectBase, object.Z), Rotation: scene.Euler{Y: object.RotationY},
				Children: []scene.Node{
					scene.Mesh{ID: object.ID, Geometry: scene.SphereGeometry{Radius: 0.13, Segments: 28}, Material: gold, Position: scene.Vec3(0, 0.13, 0), Scale: scene.Vec3(1, 1.18, 1), CastShadow: true, ReceiveShadow: true, Pickable: scene.Bool(true)},
					scene.Mesh{ID: object.ID + "-stem", Geometry: scene.CylinderGeometry{RadiusTop: 0.055, RadiusBottom: 0.07, Height: 0.24, Segments: 28}, Material: gold, Position: scene.Vec3(0, 0.39, 0), CastShadow: true, ReceiveShadow: true},
					scene.Mesh{ID: object.ID + "-neck", Geometry: scene.CylinderGeometry{RadiusTop: 0.18, RadiusBottom: 0.065, Height: 0.2, Segments: 36}, Material: gold, Position: scene.Vec3(0, 0.61, 0), CastShadow: true, ReceiveShadow: true},
					scene.Mesh{ID: object.ID + "-rim", Geometry: scene.TorusGeometry{Radius: 0.18, Tube: 0.018, RadialSegments: 12, TubularSegments: 36}, Material: gold, Position: scene.Vec3(0, 0.72, 0), CastShadow: true, ReceiveShadow: true},
				},
			})
			continue
		}
		if object.Kind == "book" {
			// A two-volume typed stack preserves the low, horizontal counterweight
			// without the notebook model's texture payload.
			darkCover := scene.StandardMaterial{Color: "#34241e", Roughness: 0.76}
			pages := scene.StandardMaterial{Color: "#c9bca9", Roughness: 0.88}
			nodes = append(nodes, scene.Group{
				ID: object.ID + "-root", Position: scene.Vec3(object.X, tabletopObjectBase, object.Z), Rotation: scene.Euler{Y: object.RotationY},
				Children: []scene.Node{
					scene.Mesh{ID: object.ID, Geometry: scene.BoxGeometry{Width: 0.56, Height: 0.045, Depth: 0.39}, Material: darkCover, Position: scene.Vec3(0, 0.0225, 0), CastShadow: true, ReceiveShadow: true, Pickable: scene.Bool(true)},
					scene.Mesh{ID: object.ID + "-pages", Geometry: scene.BoxGeometry{Width: 0.52, Height: 0.055, Depth: 0.35}, Material: pages, Position: scene.Vec3(0, 0.07, 0), CastShadow: true, ReceiveShadow: true},
					scene.Mesh{ID: object.ID + "-top", Geometry: scene.BoxGeometry{Width: 0.56, Height: 0.045, Depth: 0.39}, Material: darkCover, Position: scene.Vec3(0, 0.12, 0), CastShadow: true, ReceiveShadow: true},
				},
			})
			continue
		}
		if object.Kind == "candle" {
			// The cylinder sits directly on the mapped table surface; its small
			// radius and tall body make a clear silhouette between the vessels.
			// The muted wax color keeps its highlights below the ceramic's.
			nodes = append(nodes, scene.Mesh{
				ID: object.ID, Geometry: scene.CylinderGeometry{RadiusTop: 0.12, RadiusBottom: 0.14, Height: 0.58, Segments: 32},
				Material: scene.StandardMaterial{Color: "#bca88e", Roughness: 0.76}, Position: scene.Vec3(object.X, tabletopObjectBase+0.29, object.Z),
				CastShadow: true, ReceiveShadow: true, Pickable: scene.Bool(true),
			})
			continue
		}
		if object.Kind == "orb" {
			// This satin sphere adds a low, warm counterweight.
			nodes = append(nodes, scene.Mesh{
				ID: object.ID, Geometry: scene.SphereGeometry{Radius: 0.24, Segments: 32},
				Material: scene.StandardMaterial{Color: "#9d7557", Roughness: 0.3, Clearcoat: 0.26}, Position: scene.Vec3(object.X, tabletopObjectBase+0.24, object.Z),
				CastShadow: true, ReceiveShadow: true, Pickable: scene.Bool(true),
			})
			continue
		}
		model := tabletopKinds[object.Kind]
		model.ID = object.ID
		model.Position = scene.Vec3(object.X, tabletopObjectBase, object.Z)
		model.Rotation = scene.Euler{Y: object.RotationY}
		scale := modelScale[object.Kind]
		if scale <= 0 {
			scale = 1
		}
		model.Scale = scene.Vec3(scale, scale, scale)
		model.Bounds = modelBounds[object.Kind]
		model.Fit = "contain"
		model.FitAlign = "center-bottom"
		model.CastShadow = true
		model.ReceiveShadow = true
		model.Pickable = scene.Bool(true)
		nodes = append(nodes, model)
	}
	// The scene graph itself is fixed for every visitor in this room. Ambient
	// camera rotation stops automatically under prefers-reduced-motion.
	return scene.Props{
		Width: 1100, Height: 760, Label: "Shared tabletop diorama",
		AriaLabel:  "A shared, interactive tabletop still life with six objects",
		Background: "#111214", Controls: "orbit", AutoRotate: scene.Bool(false),
		Responsive: scene.Bool(true), FillHeight: scene.Bool(false), PreferWebGPU: scene.Bool(true),
		CanvasAlpha: scene.Bool(false), UnsupportedMessage: "This device cannot start a live 3D scene. The server-rendered poster remains available.",
		ControlTarget: scene.Vec3(0, 0.52, 0), ControlMinDistance: 4.9, ControlMaxDistance: 10.8,
		MaxFPS: 120, MaxDevicePixelRatio: 1.5, MaxPixels: scene.PostFXMaxPixels720p,
		AdaptiveQuality: scene.Bool(true), AdaptiveTargetFrameMS: 16.7, AdaptiveWarmupFrames: 120,
		AdaptivePostFX: scene.Bool(true), CursorOutputSignal: "$tabletop.cursor",
		SelectionInputSignal: "$tabletop.selection",
		Camera:               scene.PerspectiveCamera{Position: scene.Vec3(3.9, 3.05, 4.4), FOV: 32, PortraitFOV: 27, Near: 0.1, Far: 80},
		// The cool blue sweep and warm horizon make the backdrop read as a lit
		// studio, while the muted lower stop sits behind the dark wood tabletop.
		Environment:         scene.Environment{AmbientColor: "#c9bca9", AmbientIntensity: 0.13, EnvIntensity: light.EnvironmentIntensity, EnvRotation: light.EnvironmentRotation, Exposure: light.Exposure, ToneMapping: "aces", IBL: tabletopIBL, Sky: &scene.Sky{Mode: "gradient", TopColor: "#65859a", HorizonColor: "#e0b993", BottomColor: "#627b8a"}},
		PostFX:              scene.PostFX{MaxPixels: scene.PostFXMaxPixels540p, Effects: []scene.PostEffect{scene.Bloom{Threshold: 0.93, Strength: 0.08, Radius: 4, Scale: 0.25}, scene.FXAA{}}},
		Shadows:             scene.Shadows{MaxPixels: scene.ShadowMaxPixels1024},
		PickSignalNamespace: "$tabletop.pick", EventSignalNamespace: "$tabletop.event",
		Graph: scene.NewGraph(nodes...),
	}
}

// tabletopContactShadow adds a compact dark footprint under each prop. The
// warm key also casts soft shadows; the small inset stays legible on both GPUs.
func tabletopContactShadow(object tabletopObject) scene.Mesh {
	width, height := 0.52, 0.44
	switch object.Kind {
	case "plant":
		width, height = 0.76, 0.64
	case "ceramic":
		width, height = 0.66, 0.6
	case "brass":
		width, height = 0.4, 0.38
	case "book":
		width, height = 0.76, 0.56
	case "candle":
		width, height = 0.42, 0.38
	case "orb":
		width, height = 0.62, 0.56
	}
	return scene.Mesh{
		ID: object.ID + "-contact-shadow", Geometry: scene.PlaneGeometry{Width: width, Height: height},
		Material: scene.FlatMaterial{Color: "#ffffff", Texture: "/tabletop/contact-shadow.png", BlendMode: scene.BlendAlpha},
		Position: scene.Vec3(object.X, tabletopSurfaceTop+tabletopContactPad/2, object.Z), Pickable: scene.Bool(false),
	}
}

func (r *Room) scenePropsWithPointersLocked() scene.Props {
	props := r.scenePropsLocked()
	ids := make([]string, 0, len(r.pointers))
	for id := range r.pointers {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		point := r.pointers[id]
		slot, ok := r.ptrSlots[id]
		if !ok {
			continue
		}
		props.Graph.Nodes = append(props.Graph.Nodes, scene.Points{
			ID:        fmt.Sprintf("tabletop-pointer-%d", slot),
			Positions: []scene.Vector3{scene.Vec3(point.WorldX, 0.09, point.WorldZ)},
			Sizes:     []float64{13}, Colors: []string{point.Color},
			MinPixelSize: 8, MaxPixelSize: 14, Opacity: 1,
			DepthWrite: false, Style: scene.PointStyleGlow,
		})
	}
	return props
}

// sceneSnapshotCommands compares the current room scene with the scene each
// visitor initially receives. The cumulative diff can replace earlier updates
// buffered while a Scene3D renderer is loading.
func (r *Room) sceneSnapshotCommandsLocked(current scene.Props) []scene.Command {
	commands := scene.DiffPropsCommands(r.initialProps, current)
	for id := uint64(len(r.objectsSeedIDs()) + 1); id <= r.nextID; id++ {
		objectID := fmt.Sprintf("object-%03d", id)
		if _, present := r.objects[objectID]; !present {
			commands = append(commands, scene.Command{Kind: scene.CommandRemoveObject, ObjectID: objectID})
		}
	}
	for slot := 0; slot < maxTabletopVisitors; slot++ {
		active := false
		for id, visitorSlot := range r.ptrSlots {
			if visitorSlot != slot {
				continue
			}
			if _, present := r.pointers[id]; present {
				active = true
			}
			break
		}
		if !active {
			commands = append(commands, scene.Command{Kind: scene.CommandRemoveObject, ObjectID: fmt.Sprintf("tabletop-pointer-%d", slot)})
		}
	}
	return commands
}

func (r *Room) objectsSeedIDs() []string {
	return []string{"prop-ceramic", "prop-brass", "prop-plant", "prop-book", "prop-candle", "prop-orb"}
}

func (r *Room) sendSceneSnapshot(clientID string) {
	r.mu.RLock()
	current := r.scenePropsWithPointersLocked()
	commands := r.sceneSnapshotCommandsLocked(current)
	revision := r.revision.Add(1)
	r.mu.RUnlock()
	r.Hub.Send(clientID, "scene:update", scene.MountCommandBatch{Revision: revision, Commands: commands})
}

func (r *Room) broadcastSceneSnapshot() {
	r.mu.RLock()
	current := r.scenePropsWithPointersLocked()
	commands := r.sceneSnapshotCommandsLocked(current)
	revision := r.revision.Add(1)
	r.mu.RUnlock()
	r.Hub.Broadcast("scene:update", scene.MountCommandBatch{Revision: revision, Commands: commands})
}

func pointerWorldPosition(x, y float64) (float64, float64) {
	worldX := (x - 0.5) * 4.0
	worldZ := (y - 0.5) * 4.0
	distance := math.Hypot(worldX, worldZ)
	if distance > 2.02 {
		worldX *= 2.02 / distance
		worldZ *= 2.02 / distance
	}
	return worldX, worldZ
}

var modelBounds = map[string]float64{
	"ceramic": 0.86,
	"brass":   0.75,
	"plant":   1.18,
	"book":    0.60,
}

// The studio assets ship at true scale. These small per-model adjustments
// balance their silhouettes on the turntable.
var modelScale = map[string]float64{
	"ceramic": 1.4,
	"brass":   1.45,
	"plant":   1.4,
	"book":    1.75,
}

type tabletopLighting struct {
	KeyColor             string
	SkyColor             string
	RimColor             string
	KeyIntensity         float64
	FillIntensity        float64
	EnvironmentIntensity float64
	EnvironmentRotation  float64
	Exposure             float64
}

func lightingPreset(name string) tabletopLighting {
	switch name {
	case "late-afternoon":
		return tabletopLighting{"#ffd1a0", "#f0c8a8", "#e3a879", 1.55, 0.42, 0.78, 1.2, 1.02}
	case "cool-studio":
		return tabletopLighting{"#e0ecff", "#bac9df", "#97acc9", 1.8, 0.46, 0.96, 2.4, 1.08}
	default:
		// Warm key with a blue sky fill and cool rim keeps the ceramics legible
		// against the gradient without driving white surfaces into clipping.
		return tabletopLighting{"#ffd9b5", "#a6bbd0", "#99b8d2", 1.7, 0.48, 0.88, 0.25, 1.02}
	}
}

func knownLightingPreset(name string) bool {
	return name == "softbox" || name == "late-afternoon" || name == "cool-studio"
}

func knownTabletopKind(kind string) bool {
	_, ok := tabletopKinds[kind]
	return ok
}

// ValidatePlacement is the server-side admission rule used before a model is
// written to the shared document.
func ValidatePlacement(kind string, x, z float64, currentObjects int) error {
	if !knownTabletopKind(kind) {
		return ErrInvalidKind
	}
	if !finite(x) || !finite(z) || math.Hypot(x, z) > tabletopSurfaceEdge {
		return ErrOutOfBounds
	}
	if currentObjects >= maxTabletopObjects {
		return ErrObjectLimit
	}
	return nil
}

func finite(value float64) bool { return !math.IsNaN(value) && !math.IsInf(value, 0) }

func (r *Room) addVisitor(clientID string, now time.Time) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, ok := r.visitors[clientID]; ok {
		r.touchLocked(now)
		return true
	}
	if len(r.visitors) >= maxTabletopVisitors {
		return false
	}
	used := make(map[int]struct{}, len(r.ptrSlots))
	for _, slot := range r.ptrSlots {
		used[slot] = struct{}{}
	}
	for slot := 0; slot < maxTabletopVisitors; slot++ {
		if _, occupied := used[slot]; !occupied {
			r.ptrSlots[clientID] = slot
			break
		}
	}
	r.visitors[clientID] = struct{}{}
	r.palette[clientID] = "ceramic"
	r.touchLocked(now)
	return true
}

func (r *Room) removeVisitor(clientID string, now time.Time) {
	r.mu.Lock()
	delete(r.visitors, clientID)
	delete(r.pointers, clientID)
	delete(r.selected, clientID)
	delete(r.palette, clientID)
	delete(r.ptrSlots, clientID)
	delete(r.rates, clientID)
	r.touchLocked(now)
	r.mu.Unlock()
}

func (r *Room) placeAt(clientID string, x, z float64, now time.Time) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, joined := r.visitors[clientID]; !joined {
		return errors.New("tabletop: visitor is not in this room")
	}
	kind := r.palette[clientID]
	if err := ValidatePlacement(kind, x, z, len(r.objects)); err != nil {
		return err
	}
	previous := r.props.SceneIR()
	r.nextID++
	id := fmt.Sprintf("object-%03d", r.nextID)
	r.objects[id] = tabletopObject{ID: id, Kind: kind, X: x, Z: z}
	if _, err := r.applyPropsLocked(previous, "place tabletop object"); err != nil {
		delete(r.objects, id)
		return err
	}
	r.selected[clientID] = id
	r.touchLocked(now)
	return nil
}

func (r *Room) mutateSelection(clientID, action string, now time.Time) {
	r.mu.Lock()
	id := r.selected[clientID]
	object, exists := r.objects[id]
	if !exists {
		r.mu.Unlock()
		return
	}
	previous := r.props.SceneIR()
	clearedSelections := make([]string, 0)
	switch action {
	case "rotate":
		object.RotationY += math.Pi / 2
		r.objects[id] = object
	case "remove":
		delete(r.objects, id)
		delete(r.selected, clientID)
		for visitor, selected := range r.selected {
			if selected == id {
				delete(r.selected, visitor)
				clearedSelections = append(clearedSelections, visitor)
			}
		}
	default:
		r.mu.Unlock()
		return
	}
	_, err := r.applyPropsLocked(previous, "edit tabletop object")
	if err != nil {
		r.objects[id] = object
	}
	r.touchLocked(now)
	r.mu.Unlock()
	if err == nil {
		r.sendMetrics("")
		for _, visitor := range clearedSelections {
			r.sendSelection(visitor)
		}
	} else {
		r.sendSelection(clientID)
	}
}

func (r *Room) applyPropsLocked(previous scene.SceneIR, reason string) ([]scene.Command, error) {
	next := r.scenePropsLocked()
	commands, _, err := r.doc.DiffScene(previous, next.SceneIR(), reason)
	if err == nil {
		r.props = next
	}
	return commands, err
}

func (r *Room) allow(clientID, category string, now time.Time, maxPerSecond int) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.touchLocked(now)
	byKind := r.rates[clientID]
	if byKind == nil {
		byKind = make(map[string]*roomRateWindow)
		r.rates[clientID] = byKind
	}
	window := byKind[category]
	if window == nil {
		window = &roomRateWindow{}
		byKind[category] = window
	}
	cutoff := now.Add(-time.Second)
	first := 0
	for first < len(window.events) && !window.events[first].After(cutoff) {
		first++
	}
	window.events = append(window.events[:0], window.events[first:]...)
	if len(window.events) >= maxPerSecond {
		return false
	}
	window.events = append(window.events, now)
	return true
}

func (r *Room) addVisitorCount() int {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return len(r.visitors)
}

func (r *Room) sendMetrics(clientID string) {
	data, err := r.doc.Doc().Save()
	if err != nil {
		return
	}
	r.mu.RLock()
	count := len(r.visitors)
	objects := len(r.objects)
	lighting := r.lighting
	r.mu.RUnlock()
	metrics := map[string]any{"visitors": count, "objects": objects, "lighting": lighting, "documentBytes": len(data)}
	if clientID == "" {
		r.Hub.Broadcast("room:ui", metrics)
	} else {
		r.Hub.Send(clientID, "room:ui", metrics)
		r.sendSelection(clientID)
	}
}

func (r *Room) sendSelection(clientID string) {
	r.mu.RLock()
	selection := r.selected[clientID]
	r.mu.RUnlock()
	r.Hub.Send(clientID, "room:selected", selection)
}

func (r *Room) broadcastPresence() {
	r.Hub.Broadcast("room:presence", map[string]any{"visitors": r.addVisitorCount()})
	r.sendMetrics("")
}

func (r *Room) touch(now time.Time) {
	r.mu.Lock()
	r.touchLocked(now)
	r.mu.Unlock()
}

func (r *Room) touchLocked(now time.Time) { r.lastUse = now }

func (r *Room) lastUsed() time.Time {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.lastUse
}

func visitorColor(id string) string {
	colors := [...]string{"#8bd5ca", "#c6a0f6", "#f5a97f", "#91d7e3", "#ed8796", "#a6da95", "#f4dbd6", "#eed49f"}
	var sum uint32
	for _, c := range id {
		sum = sum*31 + uint32(c)
	}
	return colors[int(sum)%len(colors)]
}
