#!/usr/bin/env python3
"""Emit the prebuilt runtime release integrity manifest.

The governed release workflow's runtime-publishing job runs `gosx
build-runtime OUTDIR` (cmd/gosx/runtimepaths.go), which stages the five WASM
runtime variants plus a TinyGo wasm_exec.js shim into OUTDIR with no
manifest of its own. This script hashes those staged files and writes
MANIFEST_PATH as the JSON document cmd/gosx's prebuilt runtime resolver
(cmd/gosx/runtime_prebuilt.go, function resolvePrebuiltRuntime) decodes as
perf/ouroboros.RuntimeBuildEvidence: one "measured" record per WASM variant,
each carrying its own SHA-256 and byte count plus the shared wasm_exec.js
shim's provenance. Only the fields that decoder reads are populated; every
other RuntimeBuildEvidence field a full `gosx build-runtime --ouroboros-out`
canonical evidence bundle would carry (source identity, tool versions, and
so on) is intentionally left out, because this script's only job is
publishing a verifiable release manifest, not perf/ouroboros baseline
evidence.
"""
import hashlib
import json
import os
import sys

# (variant id, file name) pairs — must match runtimeBuildTargets() in
# cmd/gosx/runtimepaths.go exactly, both the ids and the file names.
VARIANTS = [
    ("core", "gosx-runtime-core.wasm"),
    ("engine", "gosx-runtime-engine.wasm"),
    ("collab", "gosx-runtime-collab.wasm"),
    ("full", "gosx-runtime.wasm"),
    ("islands", "gosx-runtime-islands.wasm"),
]
SHIM_FILE = "wasm_exec.js"


def digest(path):
    with open(path, "rb") as f:
        data = f.read()
    return hashlib.sha256(data).hexdigest(), len(data)


def main(argv):
    if len(argv) != 3:
        print("usage: build-runtime-release-manifest.py OUTDIR MANIFEST_PATH", file=sys.stderr)
        return 2
    outdir, manifest_path = argv[1], argv[2]

    shim_path = os.path.join(outdir, SHIM_FILE)
    shim_sha256, shim_bytes = digest(shim_path)
    shim = {
        "file": SHIM_FILE,
        "sourcePath": SHIM_FILE,
        "sha256": shim_sha256,
        "bytes": shim_bytes,
    }

    variants = []
    for variant_id, file_name in VARIANTS:
        path = os.path.join(outdir, file_name)
        sha256, size = digest(path)
        variants.append(
            {
                "id": variant_id,
                "variant": variant_id,
                "status": "measured",
                "file": file_name,
                "sourcePath": file_name,
                "sha256": sha256,
                "bytes": size,
                "shim": shim,
                "selectedByRoutes": [],
            }
        )

    manifest = {
        "schemaVersion": "gosx.ouroboros.baseline.v2",
        "contractVersion": "O0.2",
        "variants": variants,
        "notes": [
            "Published by release-governed.yml's build-runtime-release job.",
            "Generated by scripts/build-runtime-release-manifest.py from a "
            "non-canonical `gosx build-runtime` output.",
        ],
    }

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    print(f"wrote {manifest_path} ({len(variants)} variants)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
