#!/usr/bin/env sh
set -eu

script_dir="$(CDPATH= cd "$(dirname "$0")" && pwd)"
check_script="${script_dir}/check-repo-hygiene.sh"
tmp_dir="$(mktemp -d)"

cleanup() {
	rm -rf "$tmp_dir"
}
trap cleanup EXIT INT TERM

make_fixture() {
	name="$1"
	repo="${tmp_dir}/${name}"
	mkdir -p "$repo"
	git -C "$repo" init --initial-branch=main >/dev/null
	git -C "$repo" config user.email "repo-hygiene-test@example.invalid"
	git -C "$repo" config user.name "Repo Hygiene Test"

	mkdir -p \
		"$repo/client/js/bootstrap-src" \
		"$repo/editor/intelligenceassets/assets" \
		"$repo/examples/gosx-docs/app/demos/beacon"

	cat >"$repo/.gitignore" <<'EOF'
/gosx-docs
/gosx-docs.exe
/cmd/buildbootstrap/buildbootstrap
/cmd/buildbootstrap/buildbootstrap.exe
/tmp/
EOF

	cat >"$repo/client/js/bootstrap-src/chunks.json" <<'EOF'
{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {
      "name": "bootstrap.js",
      "sources": [
        "bootstrap-src/source.ts"
      ]
    }
  ]
}
EOF

	printf '%s\n' "source" >"$repo/client/js/bootstrap-src/source.ts"
	printf '%s\n' "bundle" >"$repo/client/js/bootstrap.js"
	printf '%s\n' "{}" >"$repo/client/js/bootstrap.js.map"
	printf '%s\n' "gzip" >"$repo/client/js/bootstrap.js.gz"
	printf '%s\n' "brotli" >"$repo/client/js/bootstrap.js.br"
	printf '%s\n' "wasm" >"$repo/editor/intelligenceassets/assets/gotreesitter.wasm"
	printf '%s\n' "grammar" >"$repo/editor/intelligenceassets/assets/go.bin"
	printf '%s\n' "exec" >"$repo/editor/intelligenceassets/assets/wasm_exec.js"
	printf '%s\n' "package beacon" >"$repo/examples/gosx-docs/app/demos/beacon/contract.go"
	printf '%s\n' "package beacon" >"$repo/examples/gosx-docs/app/demos/beacon/evidence_test.go"

	git -C "$repo" add .
	git -C "$repo" commit -m "fixture" >/dev/null
	printf '%s\n' "$repo"
}

replace_manifest() {
	repo="$1"
	body="$2"
	printf '%s\n' "$body" >"$repo/client/js/bootstrap-src/chunks.json"
	git -C "$repo" add client/js/bootstrap-src/chunks.json
}

add_bundle_artifacts() {
	repo="$1"
	name="$2"
	printf '%s\n' "bundle" >"$repo/client/js/$name"
	printf '%s\n' "{}" >"$repo/client/js/$name.map"
	printf '%s\n' "gzip" >"$repo/client/js/$name.gz"
	printf '%s\n' "brotli" >"$repo/client/js/$name.br"
	git -C "$repo" add "client/js/$name" "client/js/$name.map" "client/js/$name.gz" "client/js/$name.br"
}

expect_pass() {
	repo="$1"
	if ! "$check_script" --root "$repo" >"${repo}.pass.out" 2>&1; then
		echo "check-repo-hygiene-test: expected pass failed for $repo" >&2
		cat "${repo}.pass.out" >&2
		exit 1
	fi
}

expect_fail() {
	name="$1"
	repo="$2"
	want="$3"
	if "$check_script" --root "$repo" >"${repo}.${name}.out" 2>&1; then
		echo "check-repo-hygiene-test: $name unexpectedly passed" >&2
		cat "${repo}.${name}.out" >&2
		exit 1
	fi
	if ! grep -F -- "$want" "${repo}.${name}.out" >/dev/null; then
		echo "check-repo-hygiene-test: $name did not mention $want" >&2
		cat "${repo}.${name}.out" >&2
		exit 1
	fi
}

repo="$(make_fixture pass)"
expect_pass "$repo"

repo="$(make_fixture tracked-gosx-docs-exe)"
printf '%s\n' "binary" >"$repo/gosx-docs.exe"
git -C "$repo" add -f gosx-docs.exe
expect_fail tracked-gosx-docs-exe "$repo" "gosx-docs.exe"

repo="$(make_fixture tracked-buildbootstrap-exe)"
mkdir -p "$repo/cmd/buildbootstrap"
printf '%s\n' "binary" >"$repo/cmd/buildbootstrap/buildbootstrap.exe"
git -C "$repo" add -f cmd/buildbootstrap/buildbootstrap.exe
expect_fail tracked-buildbootstrap-exe "$repo" "cmd/buildbootstrap/buildbootstrap.exe"

repo="$(make_fixture tracked-tmp-future)"
mkdir -p "$repo/tmp"
printf '%s\n' "future" >"$repo/tmp/future.bin"
git -C "$repo" add -f tmp/future.bin
expect_fail tracked-tmp-future "$repo" "top-level tmp paths must not be tracked"

repo="$(make_fixture missing-bootstrap-entrypoint)"
git -C "$repo" rm -f client/js/bootstrap.js >/dev/null
expect_fail missing-bootstrap-entrypoint "$repo" "client/js/bootstrap.js"

repo="$(make_fixture missing-bootstrap-sidecar)"
git -C "$repo" rm -f client/js/bootstrap.js.br >/dev/null
expect_fail missing-bootstrap-sidecar "$repo" "client/js/bootstrap.js.br"

repo="$(make_fixture missing-non-bootstrap-sidecar)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {
      "name" : "patch.js",
      "sources": [
        "bootstrap-src/source.ts"
      ]
    }
  ]
}'
add_bundle_artifacts "$repo" patch.js
git -C "$repo" rm -f client/js/patch.js.br >/dev/null
expect_fail missing-non-bootstrap-sidecar "$repo" "client/js/patch.js.br"

repo="$(make_fixture flexible-name-spacing)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {
      "name" : "relay.js",
      "sources": [
        "bootstrap-src/source.ts"
      ]
    }
  ]
}'
add_bundle_artifacts "$repo" relay.js
expect_pass "$repo"

repo="$(make_fixture duplicate-manifest-name)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {"name": "bootstrap.js", "sources": []},
    {"name": "bootstrap.js", "sources": []}
  ]
}'
expect_fail duplicate-manifest-name "$repo" "duplicate generated JS entrypoint"

repo="$(make_fixture unsafe-manifest-name)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {"name": "../evil.js", "sources": []}
  ]
}'
expect_fail unsafe-manifest-name "$repo" "safe top-level generated JS entrypoint"

repo="$(make_fixture non-js-manifest-name)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {"name": "style.css", "sources": []}
  ]
}'
expect_fail non-js-manifest-name "$repo" "must end in .js"

repo="$(make_fixture wildcard-manifest-name)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {"name": "bootstrap*.js", "sources": []}
  ]
}'
expect_fail wildcard-manifest-name "$repo" "allowed generated JS entrypoint name"

repo="$(make_fixture bracket-manifest-name)"
replace_manifest "$repo" '{
  "comment": "Generated by cmd/buildbootstrap. Do not edit by hand.",
  "chunks": [
    {"name": "[x].js", "sources": []}
  ]
}'
add_bundle_artifacts "$repo" x.js
expect_fail bracket-manifest-name "$repo" "allowed generated JS entrypoint name"

repo="$(make_fixture ignore-negation)"
printf '%s\n' "!/gosx-docs.exe" >>"$repo/.gitignore"
git -C "$repo" add .gitignore
expect_fail ignore-negation "$repo" "gosx-docs.exe"

echo "check-repo-hygiene-test: all checks passed"
