#!/usr/bin/env python3
"""Reuse Scene3D's authored honesty gate in the page-local docs loader."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
source = (root / 'client/runtime/scene3d/mount-backend.ts').read_text()
functions = []
for name in ('sceneWebGLRendererLooksMasked', 'sceneReadWebGLRendererMetadata',
             'sceneWebGLRendererLooksSoftware'):
    start = source.index('  function ' + name + '(')
    opening = source.index('{', start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    functions.append(source[start:end])
(root / 'examples/gosx-docs/app/hero-gpu.generated.js').write_text(
    '// Generated by scripts/generate-docs-hero-gpu.py from Scene3D mount-backend.ts.\n'
    '// Regenerate with go generate ./examples/gosx-docs/app.\n' + '\n\n'.join(functions) + '\n')
