// Code generated by danmuji — DO NOT EDIT.

// Router scenario probes. Compiled by danmuji into
// route/fuzz_scenarios_danmuji_test.go.
//
// Rebuild after editing:
//     danmuji build route/fuzz_scenarios.dmj

package route

import (
	"fmt"
	"github.com/odvcencio/gosx"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
)

func TestRouterSpecificityDanmujiScenarios(t *testing.T) {
//line /home/draco/work/gosx/route/fuzz_scenarios.dmj:19
	t.Parallel()
	router := NewRouter()
	router.Add(
		Route{
			Pattern: "/docs/settings",
			Handler: func(ctx *RouteContext) gosx.Node {
				return gosx.Text("static")
			},
		},
		Route{
			Pattern: "/docs/{slug}",
			Handler: func(ctx *RouteContext) gosx.Node {
				return gosx.Text("dynamic:" + ctx.Param("slug"))
			},
		},
		Route{
			Pattern: "/docs/{path...}",
			Handler: func(ctx *RouteContext) gosx.Node {
				return gosx.Text("catch:" + ctx.Param("path"))
			},
		},
	)
	handler := router.Build()
	type PathScenario struct {
		name interface{}
		body interface{}
		path interface{}
	}
	scenarios := []PathScenario{
		{name: "static route wins", body: "static", path: "/docs/settings"},
		{name: "dynamic route captures one segment", body: "dynamic:routing", path: "/docs/routing"},
		{name: "catch all captures nested tail", body: "catch:guides/routing/nested", path: "/docs/guides/routing/nested"},
	}
	for _, scenario := range scenarios {
		_scenarioName := fmt.Sprintf("%v", scenario.name)
		t.Run(_scenarioName, func(t *testing.T) {
			t.Parallel()
			body := scenario.body
			_ = body
			path := scenario.path
			_ = path
			req := httptest.NewRequest(http.MethodGet, scenario.path.(string), nil)
			res := httptest.NewRecorder()
			handler.ServeHTTP(res, req)
			//line /home/draco/work/gosx/route/fuzz_scenarios.dmj:53
			t.Run("returns the expected route body", func(t *testing.T) {
				if res.Body.String() != scenario.body.(string) {
					t.Fatalf("body = %q, want %q", res.Body.String(), scenario.body)
				}
			})
		})
	}

}

func FuzzDanmujiRouterHandlesArbitraryEscapedPaths(f *testing.F) {
	f.Add("")
	f.Add("/docs/settings")
	f.Add("/docs/guides/routing/nested")
	f.Fuzz(func(t *testing.T, rawPath string) {
		if len(rawPath) > 2048 {
			return
		}
		router := NewRouter()
		router.Add(
			Route{
				Pattern: "/docs/settings",
				Handler: func(ctx *RouteContext) gosx.Node {
					return gosx.Text("static")
				},
			},
			Route{
				Pattern: "/docs/{slug}",
				Handler: func(ctx *RouteContext) gosx.Node {
					return gosx.Text("dynamic")
				},
			},
			Route{
				Pattern: "/docs/{path...}",
				Handler: func(ctx *RouteContext) gosx.Node {
					return gosx.Text("catch")
				},
			},
		)
		requestPath := "/" + url.PathEscape(strings.TrimLeft(rawPath, "/"))
		parsed, err := url.ParseRequestURI(requestPath)
		if err != nil {
			return
		}
		req := &http.Request{Method: http.MethodGet, URL: parsed, Header: make(http.Header)}
		res := httptest.NewRecorder()
		router.Build().ServeHTTP(res, req)
	})
}
