package evalparity

// cases is the differential table every backend renders and compares.
// Organized by Category; see doc.go for the harness design and the
// Supported/Diverges/Unsupported triage contract every row commits to.
//
// A recurring shape worth naming up front: many "Unsupported[Transpile]"
// entries below share one root cause — the GSX expression grammar (shared
// by route's reflect interpreter and the VM's island DSL, both walking
// the same *ir.Program) is dynamically typed and considerably more
// permissive than Go's static type system, which is what the real Go
// compiler enforces on transpile's output. `int && int`, `string == nil`,
// and `int + float64` are all syntactically valid GSX (gosx.Compile
// accepts them) and semantically well-defined for route/VM, but none of
// them is valid Go. That gap is not a bug in any one evaluator; it is
// exactly the boundary this harness exists to make explicit instead of
// leaving implicit.
var cases = []Case{
	// --- numeric -----------------------------------------------------

	{
		ID:       "numeric_int_add_literal",
		Category: "numeric",
		Note:     "two int literals add the same everywhere",
		Expr:     "3 + 4",
		Want:     "7",
	},
	{
		ID:           "numeric_int_add_props",
		Category:     "numeric",
		Note:         "int props fields add the same everywhere",
		Expr:         "props.A + props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 4",
		PropsValue:   map[string]any{"A": 3, "B": 4},
		Want:         "7",
	},
	{
		ID:           "numeric_int_sub_props",
		Category:     "numeric",
		Note:         "int subtraction, including a negative result",
		Expr:         "props.A - props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 4, B: 10",
		PropsValue:   map[string]any{"A": 4, "B": 10},
		Want:         "-6",
	},
	{
		ID:           "numeric_int_mul_props",
		Category:     "numeric",
		Note:         "int multiplication",
		Expr:         "props.A * props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 6, B: 7",
		PropsValue:   map[string]any{"A": 6, "B": 7},
		Want:         "42",
	},
	{
		ID:       "numeric_int_div_literal",
		Category: "numeric",
		Note:     "literal int division truncates like Go",
		Expr:     "7 / 2",
		Want:     "3",
	},
	{
		ID:           "numeric_int_div_props",
		Category:     "numeric",
		Note:         "int / int truncates like Go, not float division (see route/exprlower.go's QUO fix)",
		Expr:         "props.A / props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 7, B: 2",
		PropsValue:   map[string]any{"A": 7, "B": 2},
		Want:         "3",
	},
	{
		ID:           "numeric_int_mod_props",
		Category:     "numeric",
		Note:         "int modulo",
		Expr:         "props.A % props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 10, B: 3",
		PropsValue:   map[string]any{"A": 10, "B": 3},
		Want:         "1",
	},
	{
		ID:           "numeric_float_div_props",
		Category:     "numeric",
		Note:         "float / float keeps the fractional result",
		Expr:         "props.A / props.B",
		PropsFields:  "A float64\nB float64",
		PropsLiteral: "A: 7.5, B: 2.0",
		PropsValue:   map[string]any{"A": 7.5, "B": 2.0},
		Want:         "3.75",
	},
	{
		ID:       "numeric_mixed_literal_add",
		Category: "numeric",
		Note:     "untyped int + untyped float constants promote to float, same everywhere",
		Expr:     "3 + 4.5",
		Want:     "7.5",
	},
	{
		ID:           "numeric_mixed_typed_add_props",
		Category:     "numeric",
		Note:         "a declared int field + a declared float64 field is invalid Go (mismatched types); route/VM both coerce dynamically to float and agree",
		Expr:         "props.A + props.F",
		PropsFields:  "A int\nF float64",
		PropsLiteral: "A: 3, F: 4.5",
		PropsValue:   map[string]any{"A": 3, "F": 4.5},
		Want:         "7.5",
		Unsupported: map[Backend]string{
			Transpile: `real Go rejects "invalid operation: props.A + props.F (mismatched types int and float64)"; route/VM erase the Go static type at props-transport time and add as float64 either way`,
		},
	},
	{
		ID:       "numeric_float_format_large",
		Category: "numeric",
		Note:     "large float literal formats in scientific notation the same way in Go's fmt and strconv.FormatFloat('g', -1, 64)",
		Expr:     "100000000.0",
		Want:     "1e+08",
	},
	{
		ID:       "numeric_float_format_small",
		Category: "numeric",
		Note:     "small float literal keeps decimal notation",
		Expr:     "0.0001",
		Want:     "0.0001",
	},
	{
		ID:       "numeric_float_negative",
		Category: "numeric",
		Note:     "negative float literal",
		Expr:     "-3.5",
		Want:     "-3.5",
	},
	{
		ID:       "numeric_float_repeating",
		Category: "numeric",
		Note:     "a repeating-decimal float division formats identically (shortest round-trip representation, both strconv and fmt)",
		Expr:     "1.0 / 3.0",
		Want:     "0.3333333333333333",
	},
	{
		ID:           "numeric_precision_large_int",
		Category:     "numeric",
		Note:         "a bare props.A read (no arithmetic) preserves full int64 precision on every backend — reflect and JSON round-trips both pass the exact value through untouched. Arithmetic is what loses precision: route's numericValue and the VM's Value both fold every number through a float64 field, which cannot represent 2^53+1 exactly; transpile keeps the real Go int64",
		Expr:         "props.A + 0",
		PropsFields:  "A int64",
		PropsLiteral: "A: 9007199254740993",
		PropsValue:   map[string]any{"A": int64(9007199254740993)},
		Want:         "9007199254740993",
		Diverges: map[Backend]string{
			Route: "9.007199254740992e+15",
			VM:    "9007199254740992",
		},
		DivergesReason: map[Backend]string{
			Route: "route/fileeval.go's applyFileBinaryOp ADD always returns numericValue(left)+numericValue(right) as a bare float64, which cannot represent 2^53+1 exactly (rounds to 9007199254740992) and then formats through fmt.Sprint's large-magnitude float path as scientific notation",
			VM:    "client/vm/value.go's Value packs every number into a float64 num field; Add keeps the TypeInt tag when both operands are int-kind, but the value it carries already rounded to the nearest representable float64 (9007199254740992) before Add ever ran",
		},
	},

	// --- string --------------------------------------------------------

	{
		ID:       "string_concat_literal",
		Category: "string",
		Note:     "plain string concatenation",
		Expr:     `"foo" + "bar"`,
		Want:     "foobar",
	},
	{
		ID:           "string_concat_props_and_literal",
		Category:     "string",
		Note:         "string prop concatenated with a literal",
		Expr:         `props.S + "!"`,
		PropsFields:  "S string",
		PropsLiteral: `S: "hello"`,
		PropsValue:   map[string]any{"S": "hello"},
		Want:         "hello!",
	},
	{
		ID:       "string_eq_literal_true",
		Category: "string",
		Note:     "string equality, literal true case",
		Expr:     `"a" == "a"`,
		Want:     "true",
	},
	{
		ID:           "string_eq_props_false",
		Category:     "string",
		Note:         "string equality, props false case",
		Expr:         `props.S == "z"`,
		PropsFields:  "S string",
		PropsLiteral: `S: "hello"`,
		PropsValue:   map[string]any{"S": "hello"},
		Want:         "false",
	},
	{
		ID:       "string_lt_lexicographic",
		Category: "string",
		Note:     "string < is lexicographic byte comparison",
		Expr:     `"apple" < "banana"`,
		Want:     "true",
	},
	{
		ID:       "string_neq_literal",
		Category: "string",
		Note:     "string inequality",
		Expr:     `"a" != "b"`,
		Want:     "true",
	},
	{
		ID:       "string_empty_concat",
		Category: "string",
		Note:     "concatenating with an empty string literal is a no-op",
		Expr:     `"" + "x"`,
		Want:     "x",
	},
	{
		ID:           "string_len_builtin",
		Category:     "string",
		Note:         "len(string): the island DSL has a builtin OpLen opcode; route's CallExpr path only resolves bound Funcs/component identifiers, so the unbound \"len\" identifier evaluates to nil and the call silently renders empty",
		Expr:         "len(props.S)",
		PropsFields:  "S string",
		PropsLiteral: `S: "hello"`,
		PropsValue:   map[string]any{"S": "hello"},
		Want:         "5",
		Diverges: map[Backend]string{
			Route: "",
		},
		DivergesReason: map[Backend]string{
			Route: `route/exprlower.go's CallExpr case lowers node.Fun (the identifier "len") the same way any other identifier lowers; nothing in route/fileeval.go registers a "len" builtin, so it resolves to a nil function and callValue silently returns nil`,
		},
	},

	// --- comparison ------------------------------------------------------

	{
		ID:           "comparison_int_eq_true",
		Category:     "comparison",
		Note:         "int equality",
		Expr:         "props.A == props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 3",
		PropsValue:   map[string]any{"A": 3, "B": 3},
		Want:         "true",
	},
	{
		ID:           "comparison_int_neq_true",
		Category:     "comparison",
		Note:         "int inequality",
		Expr:         "props.A != props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 4",
		PropsValue:   map[string]any{"A": 3, "B": 4},
		Want:         "true",
	},
	{
		ID:           "comparison_int_lt_true",
		Category:     "comparison",
		Note:         "int less-than",
		Expr:         "props.A < props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 4",
		PropsValue:   map[string]any{"A": 3, "B": 4},
		Want:         "true",
	},
	{
		ID:           "comparison_int_gt_false",
		Category:     "comparison",
		Note:         "int greater-than, false case",
		Expr:         "props.A > props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 4",
		PropsValue:   map[string]any{"A": 3, "B": 4},
		Want:         "false",
	},
	{
		ID:           "comparison_int_gte_equal",
		Category:     "comparison",
		Note:         ">= at the equal boundary",
		Expr:         "props.A >= props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 4, B: 4",
		PropsValue:   map[string]any{"A": 4, "B": 4},
		Want:         "true",
	},
	{
		ID:           "comparison_int_lte_equal",
		Category:     "comparison",
		Note:         "<= at the equal boundary",
		Expr:         "props.A <= props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 4, B: 4",
		PropsValue:   map[string]any{"A": 4, "B": 4},
		Want:         "true",
	},
	{
		ID:       "comparison_float_eq_literal",
		Category: "comparison",
		Note:     "float equality",
		Expr:     "7.0 == 7.0",
		Want:     "true",
	},
	{
		ID:           "comparison_bool_eq_props",
		Category:     "comparison",
		Note:         "bool equality",
		Expr:         "props.Flag == true",
		PropsFields:  "Flag bool",
		PropsLiteral: "Flag: true",
		PropsValue:   map[string]any{"Flag": true},
		Want:         "true",
	},

	// --- ternary / conditional sugar ------------------------------------

	{
		ID:           "ternary_plain_value",
		Category:     "ternary",
		Note:         "GSX-only ternary (Go has none) on a plain (non-JSX) value",
		Expr:         `props.Flag ? "yes" : "no"`,
		PropsFields:  "Flag bool",
		PropsLiteral: "Flag: true",
		PropsValue:   map[string]any{"Flag": true},
		Want:         "yes",
		Unsupported: map[Backend]string{
			Transpile: `GSX ternary "?:" is not valid Go syntax; transpile.go has no lowering for gsx_ternary_expression, so Transpile fails with "illegal character U+003F '?'"`,
		},
		Diverges: map[Backend]string{
			Route: "",
		},
		DivergesReason: map[Backend]string{
			Route: `go/parser.ParseExpr rejects the "?" token the same way transpile does, but compiledFileExpr (route/exprcache.go) treats any parse failure as "render empty" instead of surfacing an error, so the hole silently renders nothing instead of "yes"`,
		},
	},
	{
		ID:           "ternary_jsx_both_branches",
		Category:     "ternary",
		Note:         "ternary with a JSX element on both branches lowers to two <If> subtrees (ir/lower.go's lowerConditionalExprContainer); route/VM agree",
		Expr:         `props.Flag ? <span>yes</span> : <b>no</b>`,
		PropsFields:  "Flag bool",
		PropsLiteral: "Flag: true",
		PropsValue:   map[string]any{"Flag": true},
		Want:         "<span>yes</span>",
		Unsupported: map[Backend]string{
			Transpile: `GSX ternary "?:" is not valid Go syntax and transpile.go has no JSX-conditional lowering either; author <If cond={...}>...</If> instead for a transpile-safe conditional`,
		},
	},
	{
		ID:           "and_jsx_conditional_true",
		Category:     "ternary",
		Note:         "GSX's `cond && <jsx>` sugar (not real Go's &&) mounts the element when true; route/VM agree",
		Expr:         "props.Flag && <span>yes</span>",
		PropsFields:  "Flag bool",
		PropsLiteral: "Flag: true",
		PropsValue:   map[string]any{"Flag": true},
		Want:         "<span>yes</span>",
		Unsupported: map[Backend]string{
			Transpile: `transpile.go has no lowering for the "cond && <jsx>" structural sugar; it emits the JSX element's "<" byte-for-byte into a Go expression position, which fails to parse ("expected operand, found '<'")`,
		},
	},
	{
		ID:           "and_jsx_conditional_false",
		Category:     "ternary",
		Note:         "same sugar, false case renders nothing",
		Expr:         "props.Flag && <span>yes</span>",
		PropsFields:  "Flag bool",
		PropsLiteral: "Flag: false",
		PropsValue:   map[string]any{"Flag": false},
		Want:         "",
		Unsupported: map[Backend]string{
			Transpile: `same as and_jsx_conditional_true: transpile has no lowering for this sugar`,
		},
	},

	// --- indexing --------------------------------------------------------

	{
		ID:           "index_slice_inbounds",
		Category:     "indexing",
		Note:         "slice indexing in bounds",
		Expr:         "props.Items[1]",
		PropsFields:  "Items []int",
		PropsLiteral: "Items: []int{10, 20, 30}",
		PropsValue:   map[string]any{"Items": []int{10, 20, 30}},
		Want:         "20",
	},
	{
		ID:           "index_map_present",
		Category:     "indexing",
		Note:         "map indexing, present key",
		Expr:         `props.M["k"]`,
		PropsFields:  "M map[string]int",
		PropsLiteral: `M: map[string]int{"k": 42}`,
		PropsValue:   map[string]any{"M": map[string]int{"k": 42}},
		Want:         "42",
	},
	{
		ID:           "index_slice_out_of_range",
		Category:     "indexing",
		Note:         "out-of-range slice index: real Go panics at runtime (recovered by the harness — see caseCallLine); route fails soft to \"\", VM fails soft to the element type's zero value. Documented, not fixed: ir/lower.go's strict-renderer validator already refuses index expressions for exactly this reason (\"out-of-range behavior differs from Go\")",
		Expr:         "props.Items[9]",
		PropsFields:  "Items []int",
		PropsLiteral: "Items: []int{10, 20, 30}",
		PropsValue:   map[string]any{"Items": []int{10, 20, 30}},
		Want:         "0",
		Unsupported: map[Backend]string{
			Transpile: "real Go panics at runtime: \"index out of range [9] with length 3\"",
		},
		Diverges: map[Backend]string{
			Route: "",
		},
		DivergesReason: map[Backend]string{
			Route: "route/fileeval.go's indexSequentialValue returns the zero any (nil) past the slice bound instead of erroring, which renders as empty text rather than a zero-valued element",
		},
	},
	{
		ID:           "index_map_missing_key",
		Category:     "indexing",
		Note:         "missing map key: real Go returns the value type's zero value at compile-checked type, matching VM; route fails soft to \"\" the same way index_slice_out_of_range does",
		Expr:         `props.M["missing"]`,
		PropsFields:  "M map[string]int",
		PropsLiteral: `M: map[string]int{"k": 42}`,
		PropsValue:   map[string]any{"M": map[string]int{"k": 42}},
		Want:         "0",
		Diverges: map[Backend]string{
			Route: "",
		},
		DivergesReason: map[Backend]string{
			Route: "route/fileeval.go's indexMapValue (via mapLookup) returns nil for a missing key instead of the value type's zero value, which renders as empty text instead of \"0\"",
		},
	},
	{
		ID:           "index_nested_struct_field",
		Category:     "indexing",
		Note:         "field access on a nested named-struct props field",
		Expr:         "props.Nested.X",
		ExtraTypes:   "type NestedIndexFields struct {\n\tX int\n}",
		PropsFields:  "Nested NestedIndexFields",
		PropsLiteral: "Nested: NestedIndexFields{X: 5}",
		PropsValue:   map[string]any{"Nested": map[string]any{"X": 5}},
		Want:         "5",
	},

	// --- bool coercion -----------------------------------------------

	{
		ID:           "bool_and_nonbool_int_truthy",
		Category:     "bool-coercion",
		Note:         "&& on two nonzero int props: Go's && requires bool operands, but the GSX grammar does not. route coerces via truthy(); VM's Value.truth() used to answer false for every non-bool kind (only BoolVal(true) ever set the tag bit) — fixed in client/vm/value.go, locked by TestValueTruthNonBoolKinds",
		Expr:         "props.A && props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 3, B: 5",
		PropsValue:   map[string]any{"A": 3, "B": 5},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: `real Go rejects "invalid operation: operator && not defined on props.A (variable of type int)"`,
		},
	},
	{
		ID:           "bool_and_nonbool_int_falsy",
		Category:     "bool-coercion",
		Note:         "&& with one zero int operand",
		Expr:         "props.A && props.B",
		PropsFields:  "A int\nB int",
		PropsLiteral: "A: 0, B: 5",
		PropsValue:   map[string]any{"A": 0, "B": 5},
		Want:         "false",
		Unsupported: map[Backend]string{
			Transpile: "same as bool_and_nonbool_int_truthy: real Go rejects && on int operands",
		},
	},
	{
		ID:           "bool_not_nonbool_string_empty",
		Category:     "bool-coercion",
		Note:         "! on an empty string prop",
		Expr:         "!props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: ""`,
		PropsValue:   map[string]any{"S": ""},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: `real Go rejects "invalid operation: operator ! not defined on props.S (variable of type string)"`,
		},
	},
	{
		ID:           "bool_not_nonbool_string_nonempty",
		Category:     "bool-coercion",
		Note:         "! on a non-empty string prop",
		Expr:         "!props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: "x"`,
		PropsValue:   map[string]any{"S": "x"},
		Want:         "false",
		Unsupported: map[Backend]string{
			Transpile: "same as bool_not_nonbool_string_empty: real Go rejects ! on a string operand",
		},
	},
	{
		ID:           "bool_or_nonbool_string_fallback",
		Category:     "bool-coercion",
		Note:         "|| on a non-empty string prop short-circuits to that prop, JS-template style",
		Expr:         `props.S || "fallback"`,
		PropsFields:  "S string",
		PropsLiteral: `S: "x"`,
		PropsValue:   map[string]any{"S": "x"},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: `real Go rejects "invalid operation: operator || not defined on props.S (variable of type string)"`,
		},
	},
	{
		ID:           "bool_not_nonbool_string_word_false",
		Category:     "bool-coercion",
		Note:         `! on a string prop holding the word "false": route's truthy() (route/fileeval.go) and the VM's valueTruthy (client/vm/vm.go) both fold "0" and "false" to false, not just "". Value.truth()'s kindString case (client/vm/value.go) used to check only string length, so a non-empty "false" prop stayed truthy through &&/||/! — fixed alongside bool_and_nonbool_string_zero_literal.`,
		Expr:         "!props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: "false"`,
		PropsValue:   map[string]any{"S": "false"},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: "same as bool_not_nonbool_string_empty: real Go rejects ! on a string operand",
		},
	},
	{
		ID:           "bool_and_nonbool_string_zero_literal",
		Category:     "bool-coercion",
		Note:         `&& where the left string prop holds "0" (falsy, same rule as bool_not_nonbool_string_word_false) and the right holds a truthy string: the whole expression must be false, not short-circuit true on left operand length alone.`,
		Expr:         "props.S && props.T",
		PropsFields:  "S string\nT string",
		PropsLiteral: `S: "0", T: "y"`,
		PropsValue:   map[string]any{"S": "0", "T": "y"},
		Want:         "false",
		Unsupported: map[Backend]string{
			Transpile: "same as bool_and_nonbool_int_truthy: real Go rejects && on string operands",
		},
	},

	// --- nil -------------------------------------------------------------

	{
		ID:           "nil_eq_empty_string",
		Category:     "nil",
		Note:         `route treats nil as == "" for a string comparison (route/fileeval.go's equalValues doc comment); the VM's island DSL parser accepts a bare "nil" identifier and evaluates it the same way in practice`,
		Expr:         "props.S == nil",
		PropsFields:  "S string",
		PropsLiteral: `S: ""`,
		PropsValue:   map[string]any{"S": ""},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: `real Go rejects "invalid operation: props.S == nil (mismatched types string and untyped nil)"`,
		},
	},
	{
		ID:           "nil_eq_nonempty_string",
		Category:     "nil",
		Note:         "same rule, false case",
		Expr:         "props.S == nil",
		PropsFields:  "S string",
		PropsLiteral: `S: "x"`,
		PropsValue:   map[string]any{"S": "x"},
		Want:         "false",
		Unsupported: map[Backend]string{
			Transpile: "same as nil_eq_empty_string: real Go rejects comparing a string to untyped nil",
		},
	},
	{
		ID:           "nil_neq_string",
		Category:     "nil",
		Note:         "!= nil is the complement of == nil",
		Expr:         "props.S != nil",
		PropsFields:  "S string",
		PropsLiteral: `S: "x"`,
		PropsValue:   map[string]any{"S": "x"},
		Want:         "true",
		Unsupported: map[Backend]string{
			Transpile: "same as nil_eq_empty_string: real Go rejects comparing a string to untyped nil",
		},
	},

	// --- HTML escaping ---------------------------------------------------

	{
		ID:           "escape_angle_brackets",
		Category:     "html-escape",
		Note:         "< and > escape identically everywhere (gosx.RenderHTML, route's renderFileEvaluatedExpr, and island.RenderResolvedHTML all call html.EscapeString on scalar expression text)",
		Expr:         "props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: "<script>"`,
		PropsValue:   map[string]any{"S": "<script>"},
		Want:         "&lt;script&gt;",
	},
	{
		ID:           "escape_ampersand",
		Category:     "html-escape",
		Note:         "& escapes to &amp;",
		Expr:         "props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: "Q&A"`,
		PropsValue:   map[string]any{"S": "Q&A"},
		Want:         "Q&amp;A",
	},
	{
		ID:           "escape_double_quote",
		Category:     "html-escape",
		Note:         `double quote escapes to &#34;`,
		Expr:         "props.S",
		PropsFields:  "S string",
		PropsLiteral: `S: "say \"hi\""`,
		PropsValue:   map[string]any{"S": `say "hi"`},
		Want:         "say &#34;hi&#34;",
	},
	{
		ID:           "escape_apostrophe",
		Category:     "html-escape",
		Note:         "apostrophe escapes to &#39;",
		Expr:         "props.S",
		PropsFields:  "S string",
		PropsLiteral: "S: \"it's\"",
		PropsValue:   map[string]any{"S": "it's"},
		Want:         "it&#39;s",
	},
	{
		ID:       "escape_concat_result",
		Category: "html-escape",
		Note:     "an expression's computed (not just a bare prop's) result still escapes",
		Expr:     `"<" + "b" + ">"`,
		Want:     "&lt;b&gt;",
	},

	// --- a few more numeric / boolean / string cases to round out coverage --

	{
		ID:           "numeric_unary_neg_props",
		Category:     "numeric",
		Note:         "unary minus on a direct int prop read (not a nested sub-expression) agrees everywhere",
		Expr:         "-props.A",
		PropsFields:  "A int",
		PropsLiteral: "A: 5",
		PropsValue:   map[string]any{"A": 5},
		Want:         "-5",
	},
	{
		ID:       "numeric_negative_literal_div",
		Category: "numeric",
		Note:     "-7 / 2: real Go and the VM truncate toward zero (-3); route's applyFileUnaryOp SUB case converts through numericValue (float64) before QUO ever sees the operand, discarding the int-ness the QUO fix (route/exprlower.go) depends on — a known, narrower-than-full-fix gap: QUO's fix only recovers int-ness from a DIRECT int operand (a struct field, a bare positive literal), not one already erased by a prior unary/binary op. Fixing that fully means every arithmetic op preserving Go's static type through the interpreter's untyped `any` pipeline, a materially bigger change than this harness's targeted QUO fix",
		Expr:     "-7 / 2",
		Want:     "-3",
		Diverges: map[Backend]string{
			Route: "-3.5",
		},
		DivergesReason: map[Backend]string{
			Route: "applyFileUnaryOp's SUB case returns -numericValue(value) (always float64); QUO's isIntegerKind check then sees a float64 left operand and falls back to float division",
		},
	},
	{
		ID:       "bool_literal_true",
		Category: "bool-coercion",
		Note:     "bare bool literal",
		Expr:     "true",
		Want:     "true",
	},
	{
		ID:       "bool_not_literal_false",
		Category: "bool-coercion",
		Note:     "! on a literal bool is ordinary Go, agrees everywhere",
		Expr:     "!false",
		Want:     "true",
	},
	{
		ID:       "string_concat_three_literals",
		Category: "string",
		Note:     "chained + associates left to right the same way everywhere",
		Expr:     `"a" + "b" + "c"`,
		Want:     "abc",
	},
	{
		ID:       "comparison_string_case_sensitive",
		Category: "comparison",
		Note:     "string equality is case-sensitive (byte comparison, not locale-aware) everywhere",
		Expr:     `"Apple" == "apple"`,
		Want:     "false",
	},
	{
		ID:       "comparison_float_neq_literal",
		Category: "comparison",
		Note:     "float inequality",
		Expr:     "7.0 != 8.0",
		Want:     "true",
	},
}
