// Code generated by danmuji — DO NOT EDIT.

// Session security scenarios. Compiled by danmuji into
// session/security_scenarios_danmuji_test.go.
//
// Rebuild after editing:
//     danmuji build session/security_scenarios.dmj

package session

import (
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestSessionCookieHardeningScenarios(t *testing.T) {
//line /home/draco/work/gosx/session/security_scenarios.dmj:16
	t.Parallel()
	type CookieModeScenario struct {
		name      interface{}
		encrypted interface{}
		rotated   interface{}
		want_v2   interface{}
	}
	scenarios := []CookieModeScenario{
		{name: "legacy signed cookie", encrypted: false, rotated: false, want_v2: false},
		{name: "encrypted current secret", encrypted: true, rotated: false, want_v2: true},
		{name: "legacy cookie rotates into encrypted current secret", encrypted: true, rotated: true, want_v2: true},
	}
	for _, scenario := range scenarios {
		_scenarioName := fmt.Sprintf("%v", scenario.name)
		t.Run(_scenarioName, func(t *testing.T) {
			t.Parallel()
			encrypted := scenario.encrypted
			_ = encrypted
			rotated := scenario.rotated
			_ = rotated
			want_v2 := scenario.want_v2
			_ = want_v2
			currentSecret := "session-dmj-current-secret-value"
			previousSecret := "session-dmj-previous-secret-value"
			current := MustNew(currentSecret, Options{
				Encrypt:         scenario.encrypted.(bool),
				PreviousSecrets: []string{previousSecret},
			})
			writer := current
			if scenario.rotated.(bool) {
				writer = MustNew(previousSecret, Options{})
			}
			writeHandler := writer.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				Current(r).Set("team", "platform")
				w.WriteHeader(http.StatusNoContent)
			}))
			writeRes := httptest.NewRecorder()
			writeHandler.ServeHTTP(writeRes, httptest.NewRequest(http.MethodGet, "/set", nil))
			cookie := writeRes.Result().Cookies()[0]
			readHandler := current.Middleware(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				_, _ = w.Write([]byte(Current(r).String("team")))
			}))
			readReq := httptest.NewRequest(http.MethodGet, "/read", nil)
			readReq.AddCookie(cookie)
			readRes := httptest.NewRecorder()
			readHandler.ServeHTTP(readRes, readReq)
			refreshed := cookie
			if cookies := readRes.Result().Cookies(); len(cookies) > 0 {
				refreshed = cookies[0]
			}
			//line /home/draco/work/gosx/session/security_scenarios.dmj:54
			t.Run("loads the signed payload", func(t *testing.T) {
				if readRes.Code != http.StatusOK {
					t.Fatalf("status = %d, want 200", readRes.Code)
				}
				if readRes.Body.String() != "platform" {
					t.Fatalf("body = %q, want platform", readRes.Body.String())
				}
			})
			//line /home/draco/work/gosx/session/security_scenarios.dmj:63
			t.Run("uses the expected cookie envelope", func(t *testing.T) {
				gotV2 := strings.HasPrefix(refreshed.Value, "v2.")
				if gotV2 != scenario.want_v2.(bool) {
					t.Fatalf("v2 envelope = %v, want %v", gotV2, scenario.want_v2)
				}
			})
			//line /home/draco/work/gosx/session/security_scenarios.dmj:70
			t.Run("rejects tampered values", func(t *testing.T) {
				corrupted := strings.Replace(refreshed.Value, ".", "x.", 1)
				if corrupted == refreshed.Value {
					corrupted = refreshed.Value + "x"
				}
				_, err := current.decode(corrupted)
				if err == nil {
					t.Fatal("tampered cookie decoded successfully")
				}
			})
		})
	}

}

func FuzzDanmujiDecodeSessionCookieNeverPanics(f *testing.F) {
	f.Add("")
	f.Add("not.a.cookie")
	f.Fuzz(func(t *testing.T, value string) {
		if len(value) > 8192 {
			return
		}
		manager := MustNew("session-dmj-probe-secret-value", Options{
			Encrypt:         true,
			PreviousSecrets: []string{"session-dmj-probe-previous"},
		})
		_, _ = manager.decode(value)
	})
}
