package docs

import (
	docsapp "m31labs.dev/gosx/examples/gosx-docs/app"
	"m31labs.dev/gosx/route"
)

const scene3dDescription = "Go-declared 3D: 28 node types, 11 geometries, 9 materials, 7 lights, 8 post effects, and a server-computed backend verdict."

func init() {
	docsapp.RegisterStaticDocsPage(
		"3D Engine",
		scene3dDescription,
		route.FileModuleOptions{
			Load: func(ctx *route.RouteContext, page route.FilePage) (any, error) {
				return map[string]any{
					"sample001":   docsapp.DocSample("scene3d/code-001.go.sample"),
					"sample002":   docsapp.DocSample("scene3d/code-002.go.sample"),
					"sample003":   docsapp.DocSample("scene3d/code-003.gosx.sample"),
					"sample004":   docsapp.DocSample("scene3d/code-004.go.sample"),
					"sample005":   docsapp.DocSample("scene3d/code-005.go.sample"),
					"sample006":   docsapp.DocSample("scene3d/code-006.gosx.sample"),
					"sample007":   docsapp.DocSample("scene3d/code-007.go.sample"),
					"sample008":   docsapp.DocSample("scene3d/code-008.go.sample"),
					"sample009":   docsapp.DocSample("scene3d/code-009.go.sample"),
					"sample010":   docsapp.DocSample("scene3d/code-010.go.sample"),
					"sample011":   docsapp.DocSample("scene3d/code-011.go.sample"),
					"sample012":   docsapp.DocSample("scene3d/code-012.go.sample"),
					"sample013":   docsapp.DocSample("scene3d/code-013.go.sample"),
					"sample014":   docsapp.DocSample("scene3d/code-014.go.sample"),
					"sample015":   docsapp.DocSample("scene3d/code-015.go.sample"),
					"sample016":   docsapp.DocSample("scene3d/code-016.go.sample"),
					"sample017":   docsapp.DocSample("scene3d/code-017.go.sample"),
					"sample018":   docsapp.DocSample("scene3d/code-018.go.sample"),
					"sample019":   docsapp.DocSample("scene3d/code-019.go.sample"),
					"sample020":   docsapp.DocSample("scene3d/code-020.go.sample"),
					"sample021":   docsapp.DocSample("scene3d/code-021.go.sample"),
					"sample022":   docsapp.DocSample("scene3d/code-022.go.sample"),
					"sample023":   docsapp.DocSample("scene3d/code-023.go.sample"),
					"sample024":   docsapp.DocSample("scene3d/code-024.go.sample"),
					"sample025":   docsapp.DocSample("scene3d/code-025.gosx.sample"),
					"sample026":   docsapp.DocSample("scene3d/code-026.css.sample"),
					"sample027":   docsapp.DocSample("scene3d/code-027.go.sample"),
					"sample028":   docsapp.DocSample("scene3d/gpu-driven.go.sample"),
					"sample029":   docsapp.DocSample("scene3d/code-028.go.sample"),
					"sample030":   docsapp.DocSample("scene3d/code-029.go.sample"),
					"sample031":   docsapp.DocSample("scene3d/code-030.go.sample"),
					"sample032":   docsapp.DocSample("scene3d/code-031.go.sample"),
					"sample033":   docsapp.DocSample("scene3d/code-032.go.sample"),
					"sample034":   docsapp.DocSample("scene3d/code-033.go.sample"),
					"sample035":   docsapp.DocSample("scene3d/code-034.go.sample"),
					"sample036":   docsapp.DocSample("scene3d/code-035.go.sample"),
					"sample037":   docsapp.DocSample("scene3d/code-036.go.sample"),
					"sample038":   docsapp.DocSample("scene3d/code-037.go.sample"),
					"sample039":   docsapp.DocSample("scene3d/code-038.go.sample"),
					"sample040":   docsapp.DocSample("scene3d/code-039.go.sample"),
					"sample041":   docsapp.DocSample("scene3d/code-040.go.sample"),
					"sample042":   docsapp.DocSample("scene3d/code-041.go.sample"),
					"sample043":   docsapp.DocSample("scene3d/code-042.go.sample"),
					"sample044":   docsapp.DocSample("scene3d/code-043.go.sample"),
					"sample045":   docsapp.DocSample("scene3d/code-044.go.sample"),
					"sample046":   docsapp.DocSample("scene3d/code-045.go.sample"),
					"sample047":   docsapp.DocSample("scene3d/code-046.go.sample"),
					"sample048":   docsapp.DocSample("scene3d/code-047.go.sample"),
					"sample049":   docsapp.DocSample("scene3d/code-048.bash.sample"),
					"sample050":   docsapp.DocSample("scene3d/code-049.go.sample"),
					"mode":        "",
					"title":       "3D Engine",
					"description": scene3dDescription,
					"tags": []string{
						"3d", "webgpu", "webgl", "pbr", "scene-graph",
						"raycasting", "post-processing", "selena",
					},
					"toc": []map[string]string{
						{"href": "#scene-graph", "label": "Scene Graph"},
						{"href": "#no-hierarchical-scale", "label": "No Hierarchical Scale"},
						{"href": "#backends", "label": "Backends & Verdicts"},
						{"href": "#camera-controls", "label": "Camera & Controls"},
						{"href": "#geometry", "label": "Geometry"},
						{"href": "#materials", "label": "Materials"},
						{"href": "#selena", "label": "Selena Shaders"},
						{"href": "#lights", "label": "Lights"},
						{"href": "#shadows", "label": "Shadows"},
						{"href": "#post-processing", "label": "Post-processing"},
						{"href": "#animation", "label": "Animation"},
						{"href": "#transitions", "label": "Transitions"},
						{"href": "#css-scene-state", "label": "CSS-driven Scene State"},
						{"href": "#instancing", "label": "Instancing & LOD"},
						{"href": "#particles", "label": "Points & Particles"},
						{"href": "#water", "label": "Water Simulation"},
						{"href": "#overlays", "label": "Labels, Sprites & HTML"},
						{"href": "#gltf", "label": "glTF Loading"},
						{"href": "#compression", "label": "Compression"},
						{"href": "#raycasting", "label": "Raycasting & Picking"},
						{"href": "#helpers", "label": "Helpers & Editors"},
						{"href": "#physics-audio", "label": "Physics & Audio"},
						{"href": "#quality", "label": "Adaptive Quality"},
						{"href": "#streaming", "label": "Streaming Mutations"},
						{"href": "#native-preview", "label": "Native Preview"},
						{"href": "#assets", "label": "Asset Planning"},
						{"href": "#full-stack-3d", "label": "Full-Stack 3D"},
						{"href": "#node-index", "label": "Node Type Index"},
					},
					"demoScene": DemoScene(),
					"next": map[string]string{
						"href":  "/docs/scene3d-vs-threejs",
						"label": "Scene3D vs three.js",
					},
				}, nil
			},
		},
	)
}
